### ISSUE TITLE
TWO Thursday Office Hours @ 3-5pm AND 8-10pm CSIL

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2016-Winter-Forum#104]
Please let me know if you're going to join in one, or even both, of the office hours tomorrow. 

Hopefully, this will give all of those students who have to work or attend evening classes the opportunity to attend at least one session, per your requests. :-)

**Comment by cjhodnefield** [comment]
@bobby-digital-23 I'll be at the later session. :)

**Comment by nicholasfasolt** [comment]
@bobby-digital-23 see you there as well!

**Comment by aaizuss** [comment]
@bobby-digital-23 I plan on going to the later session

**Comment by bobby-digital-23** [comment]
Thank you for responding @aaizuss @nicholasfasolt @cjhodnefield ! See you all tonight. :-)

Any takers for this afternoon? I'm here now in North Outboards (right next to CSIL 4).

**Comment by cjhodnefield** [comment]
For those that are coming to the later session, does anyone actually need the computers in Crerar? If not, could we consider relocating to Ryerson? As someone that already has to be late, due to a class ending at 8:30, this would be helpful for optimizing my time at office hours.

**Comment by chuanxix** [comment]
I will be there for the later session. Ryerson and CSIL both work for me.

**Comment by hbennett766** [comment]
I'll be at the later session, either place works

**Comment by bobby-digital-23** [comment]
Let's all meet at CSIL tonight please. 

I would have to first inquire as to whether we could meet in Ryerson in the future weeks. If tonight's evening office hours work better, I'd be happy to change the time/location for upcoming weeks. :-)

**Comment by cjhodnefield** [comment]
All right, CSIL works for me. Sorry for the last minute request to change locations. We can discuss it for future weeks.

**Comment by bobby-digital-23** [comment]
We're in CSIL 2
