### ISSUE TITLE
AllIssues... limited to 30 results.

### ISSUE THREAD

**Issue by nicholasfasolt** [uchicago-mobi/2016-Winter-Forum#107]
It looks like there is a default limit on the total number of issues that can be returned if there are more than 30. From the API documentation...

> ##### Pagination
> 
> Requests that return multiple items will be paginated to 30 items by default. You can specify further   pages with the ?page parameter. For some resources, you can also set a custom page size up to 100 with the ?per_page parameter. Note that for technical reasons not all endpoints respect the ?per_page parameter, see events for example.

[Check out this link for all the details on how to get the full list of issues](https://developer.github.com/v3/#pagination)

**Comment by tabinks** [comment]
Don't fret if you only had the 30 in your assignment.  The point of the exercise is to work with the results, whether it's 30 or 100.

**Comment by nicholasfasolt** [comment]
Great. It came up in office hours yesterday, and that's what I had figured, but also wanted to share the relevant API documentation in case anyone wanted to look into it further.
