### ISSUE TITLE
UPDATED Saturday Office Hours: 12:30-2:30pm in Young 306

### ISSUE THREAD

**Issue by danakatz** [uchicago-mobi/2016-Winter-Forum#113]

**Comment by nicholasfasolt** [comment]
Any chance this can be a little later? I won't be able to make it to HP until 1:30ish. If not, no biggie, but figured I'd ask, maybe that's true for others as well.

**Comment by cjhodnefield** [comment]
I can't make it till 1:00.

**Comment by danakatz** [comment]
@nicholasfasolt @cjhodnefield Pushed it half an hour later. See you there!

**Comment by danakatz** [comment]
308 is locked! We're in 306 (MPCS Lab B)
