### ISSUE TITLE
Static classes vs Singletons

### ISSUE THREAD

**Issue by shuaib88** [uchicago-mobi/2016-Winter-Forum#114]
last week I ended up writing networking code as a static method in a helper class. seemed to work out okay. 

I was wondering what's the advantage of using singleton classes vs static classes and I found this article: http://javarevisited.blogspot.com/2013/03/difference-between-singleton-pattern-vs-static-class-java.html

In this case it doesn't seem to matter which we use because we're not really saving any state information in the singleton class. Is that right?

**Comment by tabinks** [comment]
Read this (http://krakendev.io/blog/the-right-way-to-write-a-singleton) it will tell you more than you ever wanted to know about the behavior of singletons in Swift and the different ways to construct them...and the best way.
