### ISSUE TITLE
Present Safari View Controller Modally instead of Push

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#116]
I implemented `SFSafariViewController`, but the view controller opens with a sliding (push?) animation (the kind of animation used when transitioning between a table view cell and the detail page, for example) instead of modally. The tutorials I've looked at and the Apple Developer video show a modal transition as the default, so I don't understand why mine isn't. I've read through [this documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/index.html#//apple_ref/occ/instp/UIViewController/modalPresentationStyle) and tried to manually change the animation style using `svc.modalPresentationStyle` (svn is what I called the view controller), but I haven't gotten that to work...

**Comment by tabinks** [comment]
Check in the Storyboard how the Segue "Kind" is set.  You can toggle between modal and push here.  

<img width="286" alt="screenshot 2016-02-06 08 34 21" src="https://cloud.githubusercontent.com/assets/93689/12867184/756c4460-ccac-11e5-9701-c19f59390916.png">

**Comment by aaizuss** [comment]
@tabinks I already tried that but I didn't actually use a segue... I just used a Bar Button Item action so that option isn't available. 

![screen shot 2016-02-06 at 9 22 48 am](https://cloud.githubusercontent.com/assets/11274851/12867443/68aff5ee-ccb3-11e5-838f-74678182ba3b.png)

 I'll see if I can figure out how to make the button a segue instead of an action. The only way I know how to make a segue right now is ctrl + dragging from one view controller to another, but I don't actually have a view controller in storyboard for the safari view controller (I just have the DetailViewController).

**Comment by tabinks** [comment]
I can't seem to not have it present as modal.  If you haven't resolved it, we can review it tomorrow.

**Comment by prazgaitis** [comment]
Before calling

`self.presentViewController(safariViewController, animated: true, completion: nil)`

add this line:

`safariViewController.modalPresentationStyle = UIModalPresentationStyle.Popover`

**Comment by aaizuss** [comment]
@prazgaitis That fixed it! Thank you!
