### ISSUE TITLE
Office hours Sunday 10am to noon

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Winter-Forum#117]
Note the different time this week! CSIL doesn't open until noon, so we will be on the first floor of Crerar at one of the Mac workstations (one of the groups of 6 computers).

**Comment by tabinks** [comment]
Sounds like a great way to get ready for the big game.

**Comment by msylvester** [comment]
As far as the pregame, I'll bring my macbook pro and the latest version of Xcode.  

Superbowl Sunday party in full effect.

**Comment by lw334** [comment]
I'm here and I don't see anyone?
