### ISSUE TITLE
Office hours today TBD - Please watch for updates

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2016-Winter-Forum#12]
Apologies, I doubt I will make it today at 3pm. I'm hoping to arrive no later than 4pm but I won't know until the  battery in my car is replaced (happening as a type this). I will post an update as soon as I'm on my way. Please post any questions to the forum and one of us will try to answer them. If you have a pressing issue, email me. Thanks!

**Comment by msylvester** [comment]
Oh okay.  I am here at the CSIL.  I have the code copied verbatim from the iOS tutorial but the keyboard is not showing up.  It did during first simulations but now its not.  Any suggestions?

**Comment by danakatz** [comment]
@msylvester It might be your simulator keyboard settings. What if you go to Hardware -> Keyboard -> Toggle Software Keyboard (or just command-K)?

**Comment by bobby-digital-23** [comment]
@msylvester Just relied to your email but please try Dana's suggestion first. 

I'm about to drive to campus now and might not be able to respond for next 30-60mim. Since I will definitely arrive after 4pm, please meet in our classroom at Ryerson.
