### ISSUE TITLE
why won't UINavigationBar change it's color

### ISSUE THREAD

**Issue by shuaib88** [uchicago-mobi/2016-Winter-Forum#121]
I tried to change the nav bar appearance by calling UINavigationBar.appearance(), but this only works when I call it in appDelegate.application() In order to change the appearance I have to actually call the controller's view and change the color. This is surprising behavior -- can anyone explain what's going on. 

![screen shot 2016-02-07 at 12 03 39 pm](https://cloud.githubusercontent.com/assets/9851472/12874109/00f71e10-cd93-11e5-86db-b73942d6ff39.png)

**Comment by ghost** [comment]
I'm having a similar issue--the appearance() hook doesn't change the color of my NavBars and such, even when called in a viewDidLoad method.
