### ISSUE TITLE
Can't change height of NavigationBar

### ISSUE THREAD

**Issue by cjhodnefield** [uchicago-mobi/2016-Winter-Forum#123]
I tried to add a UINavigationBar to my CircleViewController as a way to unify the appearance between all of my tabs, but I'm unable to change its pre-defined height in the storyboard (and I can't seem to find a way to do it programmatically either). Does anyone know how to do this?

**Comment by susanstevens** [comment]
If you check StackOverflow, you'll find some hacky ways to do it (like subclassing UINavigationBar and overriding sizeThatFits).  So you _could_ do it, but Apple's deliberately making it hard to change the size of the default nav bar because they don't want you to mess with it.

**Comment by cjhodnefield** [comment]
Well, the main reason I wanted to mess with it was because the nav bar that's built into a TableViewController runs all the way to the top of the view, but dropping a nav bar onto a ViewController results in a skinnier bar that either doesn't reach the top, or can't have its text placed at the same height as the TableViewController nav bars (if that makes sense), depending on where I drag it in the storyboard. So I was just trying to standardize the way my nav bars look between the ones that are there automatically and the one I added to the circle view.

**Comment by susanstevens** [comment]
Hmmm... Yeah, it does seem like a good idea to standardize them.  What happens if instead of dragging and dropping a navigation bar, you select the CircleViewController and go to Editor -> Embed In -> Navigation Controller?

**Comment by cjhodnefield** [comment]
Oh! Yeah, that did it. I don't know why I didn't do that in the first place. Thanks!
