### ISSUE TITLE
UIView animation for activity indicator

### ISSUE THREAD

**Issue by cjhodnefield** [uchicago-mobi/2016-Winter-Forum#125]
From the 'Provide Networking Feedback' section:
"Use UIView animation to move the view on-off the screen."

Is this step necessary? At the moment, I have a UIView with a UIActivityIndicator added as a subview, and because the UIView is translucent, it is not visible on the screen when the activity indicator isn't animating. It seems like it would be unnecessary work to move it on and off the screen. Is it best practice to move it off the screen anyway when it's not in use, just in case other factors caused it to show up at the wrong time or something?

**Comment by susanstevens** [comment]
Looks the the assignment asks for a UIView with a gray background, so you should animate it coming on and off screen.  I think the point here is to practice using `UIView.animateWithDuration`.

**Comment by cjhodnefield** [comment]
Oh whoops, I missed the gray requirement at first. But yeah, I was wondering if the intent might have been for animation practice, so that's good to know. I'll get to work on animating it. Thanks!
