### ISSUE TITLE
Cells not being generated

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#126]
My singleton retrieves the data and can pass it to the View Controller, but for some reason the method

`override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell
`
isn't being called, so my table views aren't populating correctly. Anyone have a guess as to the cause?

**Comment by JRam13** [comment]
Make sure you're setting your delegate from the tableview to your view controller. You can do this in storyboard or code.

**Comment by ghost** [comment]
In the parent class, DataTableViewController, my viewDidLoad method begins with `self.view.delegate = self`, but the problem is not resolved.

**Comment by JRam13** [comment]
Try this: once you've got you data, run reloadData. Then see if numberOfSectionsInTableView is being called and what it's returning.

**Comment by ghost** [comment]
The error was caused by an unrelated issue--data was not being stored when requested from the singleton.
