### ISSUE TITLE
Will there be office hours tomorrow?

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#128]

**Comment by bobby-digital-23** [comment]
@ccook817 
The vast majority of students do not seem interested in Monday office hours. I'm basing this conclusion off of the responses to the office hours survey which Dana sent out and also by the small number of students who did attend on prior Mondays. This is why I held several sessions in both the afternoon and evening last Thursday and am planning to do the same going forward. 

However, I can hold office hours tomorrow at approx 4pm, if that would help. Please let me know and I will post the announcement.

**Comment by nicholasfasolt** [comment]
If you hold office hours tomorrow at 4, I will do my best to be there, as I have a few outstanding questions. But, please don't hold them simply on my part, only if there are others who say they will attend as well.

**Comment by ghost** [comment]
Yup, I could also be there then!

**Comment by msylvester** [comment]
Yah.  @bobby-digital-23 count me in.  I have some nagging issues
