### ISSUE TITLE
Where should we submit assignment 5?

### ISSUE THREAD

**Issue by nicholasfasolt** [uchicago-mobi/2016-Winter-Forum#129]
Should we just push our commits to the assignment 4 repository, or will there be an assignment 5 repository?

**Comment by danakatz** [comment]
@nicholasfasolt You should have a separate repo for assignment 5 - you'll find the link in https://github.com/uchicago-mobi/2016-Winter-Forum/issues/96.

**Comment by bobby-digital-23** [comment]
The professor posted this in issue #96:
https://github.com/uchicago-mobi/2016-Winter-Forum/issues/96

Think you just need to click this link:
https://classroom.github.com/assignment-invitations/d225204ec35f38dd9b96a1fcb001418d

Whoops, didn't see Dana's post first. Thanks @danakatz  😊

**Comment by nicholasfasolt** [comment]
Thank you Bobby and Dana!
