### ISSUE TITLE
Mac Apps

### ISSUE THREAD

**Issue by nicholasfasolt** [uchicago-mobi/2016-Winter-Forum#13]
Since everyone here is developing on a Mac, here's a list of a bunch of good/useful apps for Macs. It's mix of productivity, development, and a bunch of other stuff. 

https://medium.com/swlh/my-mac-apps-a5481797c634#.2chs0s4rt

**Comment by tabinks** [comment]
Thanks for sharing.  Not totally related, but be careful putting git repos in Google Drive.  I have had many problems with the repo being corrupted.  I've had good experience keeping them in Dropbox.  Although, with GitHub, you shouldn't need to worry about them being backed up.
