### ISSUE TITLE
UIActivityIndicator Nil

### ISSUE THREAD

**Issue by vhicks** [uchicago-mobi/2016-Winter-Forum#130]
I created a xib with a View and added the activity indicator and did a ctrl drag into the ui class. I am adding the view as a subview to the view controller while loading; however, I keep receiving an error that the activity indicator is Nil.

Is there some init that I need to use?

<img width="542" alt="screen shot 2016-02-08 at 9 17 16 am" src="https://cloud.githubusercontent.com/assets/16549028/12889503/c877a624-ce44-11e5-819b-1ec0f2ea4ca7.png">

**Comment by tabinks** [comment]
Check the ordering.  You're not adding it as a subview until after you do the animation.

**Comment by vhicks** [comment]
I think I am missing something very elementary, in fact most of my implementations for this build I think I am over complicating.

Do you advocate for using a xib in this instance or would programmatically be more straighforward?
