### ISSUE TITLE
Force appearance reload on Night mode button press

### ISSUE THREAD

**Issue by cjhodnefield** [uchicago-mobi/2016-Winter-Forum#132]
I've been trying to get the 'Night' mode button to work by globally changing all of the appearance() colors whenever the Night mode button is pressed in any of the view controllers. However, it doesn't change the colors appropriately until I segue to a new tab, so I'm wondering if there is a way to force the current view controller to reload its appearance upon a button being pressed.

I've tried searching for answers to this problem, and some have suggested things like using setNeedsLayout, but I can't seem to implement it correctly (or maybe that's just not the right solution here).

**Comment by prazgaitis** [comment]
Im seeing the same thing. Interested to hear what the fix is.

**Comment by lw334** [comment]
Same problem ^

**Comment by bobby-digital-23** [comment]
Hope some of these suggestions help! 🙂

In addition to `setNeedsLayout()`, have you taken a look at `setNeedsDisplay()` and/or  `layoutSubviews()`? 

If you're in a rush, I've included several links to short answers at the bottom of this post. However, please also take a look at Apple's guides and UIView class reference. A deep understanding of UIKit & UIView are crucial steps on your path to becoming great iOS developers. Btw, some of these links are included in the professor's [notes for assignment 6](http://uchicago.mobi/sessions/session6/) but they will still prove helpful for assignment 5 and every assignment (hint). 🙂

**View Programming Guide for iOS**
[View Programming Guide for iOS](https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/ViewPG_iPhoneOS/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009503-CH1-SW2)

I recommend reading, or at the very least skimming, this entire guide but if you're in a rush, check out this very useful section titled [The Runtime Interaction Model for Views](https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/ViewPG_iPhoneOS/WindowsandViews/WindowsandViews.html#//apple_ref/doc/uid/TP40009503-CH2-SW42) on the second page of that document which will hopefully help solve your issue.

**UIView Class Reference**
For specifics on how to implement UIView methods, check out the [UIView Class Reference](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIView_Class/#//apple_ref/occ/instm/UIView/). Definitely read the section titled "The View Drawing Cycle" (it's near the top of the page) and also look at the other major sections titled "Threading Considerations", "Subclassing Notes", "Methods to Override", etc.

**UIKit User Interface Catalog**
[UIKit User Interface Catalog](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/index.html#//apple_ref/doc/uid/TP40012857)
This is a handy general reference but definitely read the first page titled [About Views](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/index.html#//apple_ref/doc/uid/TP40012857-UIView-SW1). Also, quickly browse the UIKit views and controls and notice how many you have already become familiar with in such a short amount of time.

**The quick and dirty**...
...for those in a hurry. 😉

[Understanding Reload, Repaint, and Re-Layout for UITableView](http://iosdevelopertips.com/cocoa/understanding-reload-repaint-and-re-layout-for-uitableview.html)

[What is the most robust way to force a UIView to redraw?](http://stackoverflow.com/questions/1503761/what-is-the-most-robust-way-to-force-a-uiview-to-redraw)
Be careful with most of the answers to this question. I'd only read the top rated answer by Rob Napier and perhaps the answer/suggestion which directly follows it about the importance of calling UIKit class methods on the main thread (which is much more clearly explained in the "Threading Considerations" section of the [UIView Class Reference](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIView_Class/#//apple_ref/occ/instm/UIView/)).

[How does UIKit get pixels onto the screen?](https://gist.github.com/andrewsardone/3751168)
