### ISSUE TITLE
How to Snapchat Like the Teens

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#137]
Now that we know how to make an app like Snapchat,  here is a teenager to explain why it's so great:

http://www.buzzfeed.com/benrosen/how-to-snapchat-like-the-teens

And a response (from an old guy):
http://kottke.org/16/02/snapchat-like-the-teens

**Comment by msylvester** [comment]
YES!

**Comment by prazgaitis** [comment]
Wow, great article. We think we're so smart with all of our API's for detecting screenshots and all....until the teens go toss it in airplane mode, screenshot a snap, log out of the app and then we're over here running `applicationWillResignActive` before we even know what happened. You've gotta hand it to those teens!
