### ISSUE TITLE
When will our final projects be due?

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#139]

**Comment by tabinks** [comment]
March 14th.  Presentations will be during that last class session.

You will have to submit a project proposal next week.

**Comment by nicholasfasolt** [comment]
Next week as in will be due this coming Monday, or as in will be assigned this coming Monday due the following Monday?

**Comment by tabinks** [comment]
Sorry, I couldn't have made that more confusing.  It will be assigned next week in class (the 15th) and due the following week (the 22nd).

**Comment by nicholasfasolt** [comment]
Excellent, thanks for clarifying!
