### ISSUE TITLE
Office Hours - Thursday @ 3-5pm CSIL North Workgroup

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2016-Winter-Forum#141]

**Comment by bobby-digital-23** [comment]
Update: I will be there closer to 3:30pm, apologies. I will stay past 5pm if needed. 

Please let me know if you're joining. I might need your  help getting in. :-)

**Comment by chuanxix** [comment]
I will be there.

**Comment by cjhodnefield** [comment]
I'll be there, though I may also be late.

**Comment by bobby-digital-23** [comment]
Thanks!

@chuanxix
Could you please send me an email so I can contact you to get in if necessary? It's on class website. Thank you!

**Comment by ghost** [comment]
I'll also be there.
