### ISSUE TITLE
Assignment 6 not private?

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#142]
I could see other people's repos of assignment 6.

**Comment by tabinks** [comment]
I don't know why this happened.  If you can change yours to private in settings, please do.  If not, here is a new link to create a new private repo: https://classroom.github.com/assignment-invitations/d9d6da6542085439d357ca21f8cb1e8c

**Comment by nicholasfasolt** [comment]
I am not able to change the settings for the repo (or any of the repos, since I'm not the owner, I think), and clicking the link didn't do anything, apparently. There is no new private repo, just the same old not-private one.

**Comment by tabinks** [comment]
I changed them all over manually, sorry about that.

**Comment by tabinks** [comment]
@nicholasfasolt Can you check for me that you can read/write to it now?

**Comment by nicholasfasolt** [comment]
Looks good!
