### ISSUE TITLE
GitHub Org and Case Study Presentations on 20th

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#146]
You should have received a notification from GitHub about joining uchicago-mobi/mpcs51030-2016-winter organization.  Please accept this.  This will help with some of the GitHub classroom features on our end.  Thanks.

Would anyone who is planning to come to the make-up session on Saturday, February 20th at 3:00pm be interested in doing their case study that day?

**Comment by tabinks** [comment]
![](https://s3.amazonaws.com/thumbnails.illustrationsource.com/huge.101.508672.JPG)

**Comment by bobby-digital-23** [comment]
Bueller...Bueller...Bueller...
