### ISSUE TITLE
Creating Array of UIViews

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#147]
I'm trying to create the array of UIViews for the board spaces programmatically (similar to the way we created the RatingControl from the Apple FoodTracker Tutorial, but with views instead of buttons), but I'm more tempted to drag 9 UIViews into storyboard because it's easier to arrange. If I do it from storyboard, I don't know how to actually add those views to my array (do we use tags? or the restoration ID?).

**Comment by tabinks** [comment]
If you add them in storyboard you will need to create a reference to them in code (using the good ol' ctrl-drag and drop).  You will them have 9 views to manage directly by name.  

You could also reference them by tag, using the `viewWithTag` method (assuming you set unique tags in storyboard).  You would do the following:
- Get the array of subviews from the view
- Iterate through them to identify the views you want (using `viewWithTag`)
- Add those to an array

There are many different ways you can identify the views and put them into an array.  Once they are in the array, you can always use the array to reference them, so iterating through them should be straightforward.  In the end in just depends on you preference for explicitly referencing views in storyboard vs. creating them programmatically vs. referencing them by tag.
