### ISSUE TITLE
code of the demonstration in the class

### ISSUE THREAD

**Issue by cnfshandson** [uchicago-mobi/2016-Winter-Forum#148]
Hi 
Where can I download the the code of the demonstration in the class?  I mean the " flower, sun, meerkat" animation.

Thank you.

**Comment by bobby-digital-23** [comment]
Code examples are in the slides:
http://uchicago.mobi/sessions/session6/

**Comment by cnfshandson** [comment]
oh, I was looking for the Xcode text files, but if not, the slide is good enough for study purpose. thank you.

**Comment by tabinks** [comment]
The code in the slides is representative of what you should be doing and you should use it as a reference.  I did not add that the to playgrounds repo to force everyone to actually type in the code.

**Comment by tabinks** [comment]
![groundhog](https://cloud.githubusercontent.com/assets/93689/13024003/7f8b11f8-d1b4-11e5-873e-86f6defa6b7a.png)

And it was a groundhog....not a lemming.

**Comment by tabinks** [comment]
Meerkat
