### ISSUE TITLE
init functions

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#149]
I'm confused about when we need initialization functions in the ViewController. I created the custom subclass of UIImageView to use for X's and O's, which has an init method that calls `super.init(image: image)`, enables user interaction, and adds a `UIPanGestureRecognizer`. Xcode forces me to also add `required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }`.

I want to implement the required init method in my ViewController class, but I don't know what to put in it. Currently, I add my X and O images as subviews to my main view in `viewDidLoad`, and that's also where I fill the array of the UIViews, so I don't know what is left to put in the required init function. If I only call `super.init(coder: aDecoder)`, the app crashes with a fatal error (from the custom UIImageView subclass).

I looked at the FoodTracker tutorial again to see how it uses initialization functions, but it isn't helping.

**Comment by danakatz** [comment]
@aaizuss In your UIImageView subclass, you still need to update your implementation of `required init?(coder aDecoder: NSCoder)` to not throw a fatal error -- Xcode puts the error in its fix-it code to remind you to rewrite the method yourself. Try revisiting [this section](https://developer.apple.com/library/ios/referencelibrary/GettingStarted/DevelopiOSAppsSwift/Lesson5.html) of the FoodTracker tutorial.

**Comment by ghost** [comment]
I override the initializers and update the implementation but my UIPanGestureRecognizers do not recognize the pan gestures?

**Comment by susanstevens** [comment]
Remember to enable user interaction on your `UIImageView`.  The `userInteractionEnabled` property is false by default on `UIImageViews`.

**Comment by ghost** [comment]
That property is enabled but the issue persists.

**Comment by bobby-digital-23** [comment]
Short answer:
Look at the slides and you'll see what's necessary to do when you subclass UIImageView. 

Long answer:
Learn how designated initializers work, how this affects  subclasing UIImageView, and about Swift's "Automatic Intializer Inheritance"

Swift Programming Guide:

Automatic Initializer Inheritance

"As mentioned above, subclasses do not inherit their superclass initializers by default. However, superclass initializers are automatically inherited if certain conditions are met. In practice, this means that you do not need to write initializer overrides in many common scenarios, and can inherit your superclass initializers with minimal effort whenever it is safe to do so."

Still from Swift docs:

"Rule 1
If your subclass doesn’t define any designated initializers, it automatically inherits all of its superclass designated initializers.

Rule 2
If your subclass provides an implementation of all of its superclass designated initializers—either by inheriting them as per rule 1, or by providing a custom implementation as part of its definition—then it automatically inherits all of the superclass convenience initializers."

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Initialization.html#//apple_ref/doc/uid/TP40014097-CH18-ID222

UIImageView reference:

"If you are writing a custom subclass of UIImageView, you should be aware of the following behaviors:

The UIImageView class is optimized to draw its images to the display. UIImageView does not call the drawRect: method of its subclasses. If your subclass needs to include custom drawing code, you should subclass the UIView class instead.

New image view objects are configured to disregard user events by default. If you want to handle events in a custom subclass of UIImageView, you must explicitly change the value of the userInteractionEnabled property to true after initializing the object."

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImageView_Class/index.html

**Comment by ghost** [comment]
Well, I've: 

-programmatically added the PanGestureRecognizers to the subclass of UIImageView
-overriden both initializers
-ensured that userInteractionEnabled == true
-made the subclass conform to the UIGestureRecognizerDelegate
-pointed the delegate property of the programmatically-instantiated PanGestureRecognizers to 'self' during the initialization of the UIImageView

I am testing them with a block of code:

`
/*...*/
  func movePiece(gestureRecognizer: UIPanGestureRecognizer){
            print("Got pan gesture");
    }`

They are still unresponsive. This appears to be the same procedure undertaken in the slides. The UIImageView subclass objects appear in the UI but are still unresponsive.

**Comment by manglano** [comment]
<img width="616" alt="screen shot 2016-02-13 at 4 45 58 pm" src="https://cloud.githubusercontent.com/assets/6961916/13030448/5a2c66e2-d271-11e5-9efe-733999d1a392.png">

**Comment by bobby-digital-23** [comment]
Admittedly, initializers (constructors for the Java heads) can be confusing at first but learning how they work will save many frustrating hours of debugging. 

These blog posts help summarize, to varying degrees,  what the Swift Guide (linked to in last post) discusses at length:

https://objectpartners.com/2016/01/18/exploring-swift-initializers/

http://www.edwardhuynh.com/blog/2015/02/16/swift-initializer-confusion/

http://napora.org/nscoder-and-swift-initialization/

**Comment by susanstevens** [comment]
Are you adding the pan gesture recognizer in `required init?(coder aDecoder: NSCoder)`?  Or somewhere else?  You might just double-check that the gesture recognizer is being added properly.

Also, when you add the target and action to your gesture recognizer, make sure you include the semi-colon in `movePiece:`.  And if you added your `UIImageViews` in storyboard, make sure you set their class to be your custom subclass.  (I pretty much always forget to do this at least once.)

Let us know if any of this helps or if you're able to narrow down the issue any further.  Happy debugging!

**Comment by ghost** [comment]
The source of the bug: I had instantiated and added the UIPanGestureRecognizer within the UIImageView subclass instead of within the view controller, which broke with MVC & naturally just doesn't work.

**Comment by lw334** [comment]
@manglano  hmmm I think we should add it in the sub class thou. Otherwise what's the added benefit to subclass UIImageView?

**Comment by ghost** [comment]
I'm not sure there is an added benefit to subclassing UIImageView. To process a move correctly, the controller needs access to the data model, and I think it can only get that access by being a part of ViewController.

I suppose there may be another way to do it, like hold the data model in a singleton and have the UIImageView subclass interact with both the singleton and static members of the main ViewController--but that's not how I'm doing it!

EDIT: To be specific, I attach a UIPanGestureRecognizer to an instance of the subclass from within the ViewController's viewDidLoad scope, instead of from the subclass initializer scope. The specification doesn't say where to attach the GestureRecognizer, just to attach one.

**Comment by lw334** [comment]
I was looking up tutorials and came across people saying it's generally not a good practice to subclass UIImageViews. So I agree with you on doing it in the view controller because the uiimageview should only know about displaying itself. But it is possible to subclass it and add the gesture recognizer to it within the subclass. I have to work on handling the data before I can say that with confidence though. :P

**Comment by tabinks** [comment]
One reason you might want to subclass `UIImageView` would be to consolidate work that that will be done to many different instances of the image view.  In this case, you might subclass to set the default image and images:

``` swift
class xPieceImageView: UIImageView {
// Set the default image as the "X" piece
// Play sound when tapped
}

class oPieceImageView: UIImageView {
// Set the default image as the "O" piece
// Play sound when tapped
}
```

If you wanted to refactor it further, you could do:

``` swift
class pieceImageView: UIImageView {
// Play sound when tapped
}

class xPieceImageView: pieceImageView {
// Set the default image as the "X" piece
}

class oPieceImageView: pieceImageView {
// Set the default image as the "O" piece
}
```

**Comment by tabinks** [comment]
Another thing that may be useful to implement in a `UIImageView` subclass:

``` swift
 override func didMoveToSuperview() {
  // This will be called automatically when this view is added 
  // to a view hierarchy (e.g. addSubview() is called with this view as parameter)
 }
```
