### ISSUE TITLE
Auto layout constraints versus programmatically generating UIViews

### ISSUE THREAD

**Issue by nickpann** [uchicago-mobi/2016-Winter-Forum#150]
I've created my 9 views in the storyboard. Everything looks good when I run the simulator, but I get a "frame topCenter will be different at runtime" warning. This is the case for each of my 3 middle-column views.

I can't reset to the suggest constraints without creating conflicts however.

I am wondering if this is a problem. And a more underlying question is, what the best practice is considered to be when it comes to creating adjacent views. There are several ways to approach this problem: with interface builder, programmatically, collection view, etc.

**Comment by nickpann** [comment]
The constraints thing is really bothering me, because it seems like a very inelegant way of creating the grid, so I'd be happy to hear about an alternative approach before it's too late to go another direction.

**Comment by tabinks** [comment]
The easiest way would be to hard code the frames, which is a valid solution since you are only targeting a specific device.

If you want to use auto layouts, you should look at making them relative to each other (eg make same size, align top edge, etc.)

**Comment by susanstevens** [comment]
In storyboard you can change the size of your view controller to iPhone 4.7-inch in the attributes inspector.  Then your storyboard view controller will be the same size as an iPhone 6 and everything will appear on screen however it was laid out in storyboard.  Since your project only needs to run on iPhone 6, you can use this approach and avoid auto layout all together.

**Comment by nickpann** [comment]
Thanks for your comments. I initially turned off auto layout and tried to hard code the values but the simulator didn't look like the storyboard. Following Susan's advice fixed that.
