### ISSUE TITLE
Will there be office hours today in Hyde Park today? Or only tomorrow?

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#151]

**Comment by danakatz** [comment]
None today -- I'll be holding Hyde Park office hours on Saturdays when my schedule allows, probably around every other week, in addition to my regular Thursdays at Gleacher. I think @susanstevens will hold office hours tomorrow as usual.

**Comment by susanstevens** [comment]
Yes, my office hours will be tomorrow (Sunday) from 4-6pm in CSIL 1 in the Crerar Library as usual.
