### ISSUE TITLE
Sunday Office Hours 4-6pm

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Winter-Forum#152]
I'll be holding office hours at my usual time this week -- Sunday from 4-6 pm in CSIL 1 in the Crerar Library.  See you there!

**Comment by aaizuss** [comment]
I know this is short notice, but I can't make office hours today (I have a meeting from 4-6). @susanstevens Are you able to get to Crerar at 3 or 3:30? Or can someone have office hours tomorrow afternoon?
