### ISSUE TITLE
UIView Popup during Game End/Tie

### ISSUE THREAD

**Issue by gopalp19** [uchicago-mobi/2016-Winter-Forum#154]
You said we should use a custom UIView when the game ends (win or tie). Are we not allowed to use a UIAlertController like we did in the last homework?

**Comment by bobby-digital-23** [comment]
Where's the fun in that? ;-)

Check out the tip in the notes:

![screen shot 2016-02-13 at 5 53 07 pm](https://cloud.githubusercontent.com/assets/10453834/13030744/bc97f96e-d27a-11e5-8f0b-eb2b548920e1.png)

**Comment by tabinks** [comment]
See #155

**Comment by gopalp19** [comment]
Got it, thanks!
