### ISSUE TITLE
Present Modal View

### ISSUE THREAD

**Issue by lw334** [uchicago-mobi/2016-Winter-Forum#155]
Should we animate the UI View like the sun example in class to present the instruction or should we create another viewController and present it as a modal view?

**Comment by prazgaitis** [comment]
I had a similar question about this one.

From the assignment specs:

> Tip: You need to present a custom `UIView` at three different places in the app. It would be a best practice to create one that you can reuse, passing along an `NSString` with the message to display.

However, in the screenshots, it looks like the "Game Over" view is an UIAlertController. In Apple's Developer docs, it mentions that

> The UIAlertController class is intended to be used as-is and does not support subclassing. The view hierarchy for this class is private and must not be modified.

So, should we create a brand new UIView for the instructions/Game Over / Stalemate? Or would it be better to use a UIAlertController?

EDIT: Looks like this was clarified in #154

**Comment by lw334** [comment]
I just found it hard to specify the coordiantes of UILabel, UITextView, etc on a UIView programmatically. Maybe I'm not doing this right but I would much prefer laying out a UIViewController and add everything and present the viewcontroller as a modal view... Not sure if that's what the assignment wants.

**Comment by tabinks** [comment]
You should use a custom `UIView` not a `UIViewController`.  What @prazgaitis wrote is true, you should not try and customize the `UIAlertController`, for this assignment (and in general).  The screenshot from the writeup is actually a `UIView` customized to look like an alert views.  To get a similar effect:
- Use `UIView.layer.cornerRadius` property
- Adjust alpha and background color
- Use the default (system) font

@lw334 Take a look a using the `center` property of each subview to help with the alignment.  If you align all the views first at the superview's center, then you only need to adjust the `y` for each view.

**Comment by lw334** [comment]
Thanks a lot for the clarification! @tabinks
