### ISSUE TITLE
Can't change property of ViewController during the Pan Gesture

### ISSUE THREAD

**Issue by 3sands** [uchicago-mobi/2016-Winter-Forum#158]
I up to the part where after the pan gesture has ended, the letter has to snap into the frame of the correct UIView. I have an array of Booleans that I declared in the properties of the View Controller. I wanted to change this array when the frames intersect during the panLetter function in the custom UIImageView, but I keep getting an error that says "Instance member cannot be used on type "ViewController". Is it possible to access the properties here? I've been googling but haven;t been able to find anything.

**Comment by tabinks** [comment]
Sounds like you're sending the message to the wrong object.
