### ISSUE TITLE
Apple News of the Week 2

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#16]
Feel free to post anything interesting your find...

**Comment by nicholasfasolt** [comment]
Not strictly Apple news here, but I think pertinent nonetheless.

[Uber invites developers to build apps for customized passenger distractions - NYT](http://bits.blogs.nytimes.com/2016/01/12/uber-invites-developers-to-build-apps-for-customized-passenger-distractions/?emc=edit_th_20160113&nl=todaysheadlines&nlid=54053641)
