### ISSUE TITLE
Important Dates and Deadlines

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#162]
- assignment six is due Tuesday, February 16 at 11:59 PM 
-  One page project proposal is due Friday, February 19 at 11:59 PM. Right if you sentences about your app and include mock up screenshots of the main scenes.  You are welcome to use any tools to make the mock ups, including drying them by hand. 
- Office hours with Andrew from 11:30-1 on Thursday, February 18 in Young 308
-  Make up class is Saturday, February 20 from 3-6
-  assignment seven is due Monday, February 22 at 5:29 PM.

**Comment by danakatz** [comment]
- Regular weekly office hours every Thursday from 6-8pm at Gleacher.
- Saturday office hours in Hyde Park as my schedule allows -- I will post a time and location the Thursday or Friday before if I'm planning to have them that week. I'll probably have them before the makeup class on February 20 and will post more details in a few days.

**Comment by susanstevens** [comment]
My office hours are every Sunday from 4-6pm in CSIL 1 in the Crerar Library.  I'll always post on the forum if I need to reschedule the time or date of a session, but otherwise you can assume that my office hours are being held at the usual time.  (I'll still post reminders either way!)

**Comment by bobby-digital-23** [comment]
Unfortunately, I cannot do my usual afternoon Thursday office hours tomorrow. I caught a bad stomach virus. If I'm feeling better, I will do office hours before or after the lecture on Sat. I will post an update here.

**Comment by brittneyli** [comment]
How should we submit the final project proposal? Should we just send it via email?

**Comment by tabinks** [comment]
Email is fine.
