### ISSUE TITLE
API tokens and swift

### ISSUE THREAD

**Issue by msylvester** [uchicago-mobi/2016-Winter-Forum#163]
I am prepping for my final proj and want to pull from an API that requires a token.  Using the API token I have, I can make calls using Node.js without problems.

How can we update the code from projects 4 and 5 to make a network call to an API that requires a token?  

I have browsed around the web but I was wondering if anyone had any experience/suggestions.

Mike

**Comment by susanstevens** [comment]
Are you referring to an API key that identifiers your application?  In that case, it's usually appended to the url as a parameter.  

On the other hand, if you're talking about an access token that identifies a particular user (like apps that have the "sign in with Facebook" option), that's a little more complicated.  In that case, it's probably easiest to look for tutorials that use the particular API you want to incorporate.  And, of course, read the API documentation.  I'm not sure what API you're thinking of using, but some provide sample projects or step-by-step instructions that are really helpful.

**Comment by tabinks** [comment]
It really depends on what service you are using and the authentication they use.  They should have some documentation that describes what needs to be sent.  If you want to share what service it is, we can help you figure it out.
