### ISSUE TITLE
JSON Formatter

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/2016-Winter-Forum#166]
If anyone is having trouble reading this API, and has chrome, install the chrome extension "JSON Formatter." It's magical. (credit to Binkowski's office hours on that one)

**Comment by tabinks** [comment]
:+1:

**Comment by vhicks** [comment]
Any ideas why my JSON is returning in Arabic?

**Comment by susanstevens** [comment]
@vhicks Try substituting a search term for the part of the url that says `<SEARCH_TERM>`.

**Comment by vhicks** [comment]
Ha! Thanks @susanstevens 😁
