### ISSUE TITLE
No Class Next Monday?

### ISSUE THREAD

**Issue by chuanxix** [uchicago-mobi/2016-Winter-Forum#17]
We wouldn't have any class on MLK Day right? Will we have a make-up class?

**Comment by bobby-digital-23** [comment]
Yes. 
Makeup class - time/day will be posted well in advance. :-)

**Comment by tabinks** [comment]
There is no class on Monday in honor of MLK Day.  We will have a make-up class this quarter. I am working on reserving a room for it and will let everyone know as soon as possible.

**Comment by tabinks** [comment]
Forgot to mention, there will be assignment for next week.
