### ISSUE TITLE
Adding UIToolbar to UITableview

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#170]
I'm trying to make my Bookmark View editable. The view contains a UITableView (dragged in from storyboard and connected to my code) and a UIToolbar with an edit button. I dragged UIToolbar over the table view and added an edit button. This is visible in storyboard, but not when I run the app. I've implemented the table view functions to make the table editable, but the toolbar doesn't show up and gestures to delete cells aren't working either (the Apple tutorial said that when you implement the edit function, gestures to delete should work). Googling this issue hasn't helped.

**Comment by prazgaitis** [comment]
Here's what worked for me:

Drag the toolbar on first, and then put the tableview in afterwards. Mine looks like this: http://postimg.org/image/ubs3rp133/

**Comment by aaizuss** [comment]
Mine already looks like that in storyboard too, but it still doesn't show up in the app. Even when I make the table view smaller in storyboard (which visibly makes a difference in the app), the toolbar doesn't show up. But I did try removing both elements, dragging the toolbar on firs, and putting the tableview in after, and it makes no difference.

**Comment by msylvester** [comment]
@aaizuss.  We went over this the last hour of lecture.  Oh wait...

**Comment by aaizuss** [comment]
Initially, it looks like one way to do it is to select the Navigation Controller, and then in its attributes check "Shows Toolbar." Unfortunately, this toolbar appears on top of the toolbar that I had already added to my Detail View Controller, and no toolbar shows up in the Bookmark View Controller (still). I've also checked to make sure that the toolbar isn't just hidden.

**Comment by susanstevens** [comment]
Have you checked your view hierarchy?  You should be adding the toolbar to the view controller, not nested inside the table view.

**Comment by aaizuss** [comment]
@susanstevens I added it to the View in the View Controller. It's not in the table view unless I'm misunderstanding what this means: 
![screen shot 2016-02-21 at 3 44 29 pm](https://cloud.githubusercontent.com/assets/11274851/13205639/03ce6fd8-d8b2-11e5-894c-f611342f925c.png)

**Comment by shuaib88** [comment]
did you end up getting this to work? I don't think my BookMark Controller is embedded in a navigation controller? Anyone know if you need that?

**Comment by aaizuss** [comment]
@shuaib88 I got it to work by setting up a few auto layout constraints

**Comment by shuaib88** [comment]
@aaizuss  thanks -- yeah i did the same and now can see the delete

**Comment by prazgaitis** [comment]
If you're not having any issues with the popover then I wouldn't worry about it. My popover was ignoring constraints and extending downward off of the screen for some reason.
