### ISSUE TITLE
Popover problems

### ISSUE THREAD

**Issue by prazgaitis** [uchicago-mobi/2016-Winter-Forum#171]
To quote the prolific iOS developer Jay-Z: 

> If you've got popover problems I feel bad for you son...I got 99 problems but a popover view ain't one (anymore!)

Of course Jay only came to this conclusion after implementing this code:

```
func adaptivePresentationStyleForPresentationController(controller: UIPresentationController, traitCollection: UITraitCollection) -> UIModalPresentationStyle {
        return .None
    }
```

This will help if your popover is inexplicably extending past your screen.

Cheers!

**Comment by cjhodnefield** [comment]
@prazgaitis Hey, I can't seem to get this advice to work for my popover. Where did you implement that method? And did you have to make the class you implemented it in conform to any protocols?

**Comment by prazgaitis** [comment]
Yes - this code is in my DetailViewController, which conforms to UIPopoverPresentationControllerDelegate

**Comment by cjhodnefield** [comment]
Thanks! That seems to have done it.

**Comment by tabinks** [comment]
@uchicago-mobi/mpcs51030-2016-winter Everyone should pay attention to this tip.

**Comment by shuaib88** [comment]
@tabinks is this crucial? I don't seem to have this problem at all. I got my Bookmark editing to work without it

**Comment by prazgaitis** [comment]
If you're not having any issues with the popover then I wouldn't worry about it. My popover was ignoring constraints and extending downward off of the screen for some reason.
