### ISSUE TITLE
Delete Cells from Bookmark View Controller

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#173]
Has anyone successfully implemented the ability to delete items from the bookmark view controller? 
I've implemented the UITableViewDataSource Protocol methods, but I don't know how to actually hook up my edit button, which is on a Toolbar. The Apple Tutorial and other sources I've seen add the edit button programmatically to the navigation bar:
`self.navigationItem.leftBarButtonItem = self.editButtonItem()`
 but we can't do that with the bookmark view controller...

I have an outlet to my edit button called `editButton`, and I tried doing `self.editButton = self.editButtonItem()` but that has no effect.

**Comment by tabinks** [comment]
You can embed the bookmark view controller in a navigational controller to get a nav bar.

**Comment by tabinks** [comment]
Also, all the edit button does is set the table views 'editing' property to true.  You can set it to true anyway you want to get the table in editing mode.

**Comment by aaizuss** [comment]
@tabinks  It is embedded in a navigation controller - but a nav bar will appear on top, right? I assumed you wanted us to use a toolbar (based on the photo) because the edit button is on the bottom left. 

And even though I set the editing property to true and implemented the corresponding methods, I can't edit the table.

**Comment by tabinks** [comment]
@aaizuss You can implement it any way you want.  It doesn't have to be a toolbar, that was just a suggestion.  You can use a regular button (in any interface) if you want.

Call this in `viewWillAppear` and it should put the table in editing mode right away. 

``` swift
tableView.setEditing(true, animated: true)
```

This should let you know if the table is actually getting into editing mode.  You should see the editing accessories (the red circles).

**Comment by tabinks** [comment]
@aaizuss Did you figure it out?

**Comment by aaizuss** [comment]
@tabinks Yes, I got it - thanks!

**Comment by tabinks** [comment]
:+1:
