### ISSUE TITLE
Tweeting an Article

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#174]
I want to make sure I've implemented the twitter functionality the way the assignment wants us to.

When the user isn't logged in to twitter, I show a `UIAlertController` that alerts the user to log in. So the actual twitter `SLComposeViewController` doesn't show up unless the user is logged into Twitter in the simulator. Is this the proper way to handle the situation?

**Comment by tabinks** [comment]
Yes.  This is correct.  The user has to be logged in to Twitter via the system accounts for this to work.  There is no way to authorize them from the framework.  You can just tell the to log in if they are not.
