### ISSUE TITLE
Gray bar above UIWebView

### ISSUE THREAD

**Issue by chuanxix** [uchicago-mobi/2016-Winter-Forum#175]
I have a grey bar at the top of the WebView, below the navigation bar in the detail view. Don't know how to remove it.
In the storyboard, I set the constraints of the UIWebView to 0 spacing to nearing neighbors on all the dimensions.

![snip20160221_1](https://cloud.githubusercontent.com/assets/16563696/13208515/d708cb34-d8e7-11e5-9cd4-e3269c4c695d.png)

**Comment by chuanxix** [comment]
I added the UIWebView as a subview of the detail view controller. It's working now.

**Comment by tabinks** [comment]
Glad to hear it.
