### ISSUE TITLE
URGENT: Guaranteeing critical sections execute sequentially

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#176]
I am trying to ensure data loads automatically at startup and when a search term is specified; I create a concurrency thread and queue instructions using a dispatch_sync critical section for that purpose:

`dispatch_sync(concurrentNetworkQueue){
            if (searchTerm != nil){
                if (searchTerm!.characters.count > 0){
                    self.newsSourceAndDelegate?.fetchData(searchTerm!)
                }
            }
        }
        dispatch_sync(concurrentNetworkQueue){
            self.tableView.reloadData()
        }`

However, the tableView does not reload automatically with the correct data, and only reloads upon a pull-to-refresh or a successive search. I've been trying various GCD configs for about an hour now and none of them work. Does someone have a fix? I guess I could spinlock it with a While Loop...

Update: Spinlocks did not resolve the issue and dispatching critical sections to a separate concurrent thread does not guarantee sequential completion.

See also #131.

**Comment by manglano** [comment]
Update: Spinlocks did not resolve the issue and dispatching critical sections to a separate concurrent thread does not guarantee sequential completion.

**Comment by ghost** [comment]
Hi, I'm trying to implement the NSDefaults functionality and the resulting GCD threading has broken my entire app. I spent yesterday evening trying to solve the problem with a tutorial (http://www.raywenderlich.com/79149/grand-central-dispatch-tutorial-swift-part-1) but it's unenlightening and I would really appreciate some guidance.

**I don't mean to be a bother, but I've been waiting to have this question answered for more than two weeks.**

**Comment by tabinks** [comment]
The `NSUserDefaults` part shouldn't play any part in reloading your query, other than checking for state and `String`:

``` swift
// Get the string from user defaults 
let lastQueryString = defaults.stringForKey("lastQueryString")

// Pass this string as the query when launched
```

Remember that `NSURLSession` is asynchronous.  The work will be done on the background thread so the only thing you need to worry about is making sure that you tell the table to reload it's data (once its back from the request) on the main thread.

``` swift
// This should be in the NSURLSession completion closure after all the JSON processing is done
// and the data you want to show in the table has been copied to the array feeding your table
dispatch_async(dispatch_get_main_queue()) { [unowned self] in
    self.tableView.reloadData()
}
```

**Comment by tabinks** [comment]
This is not a complete implementation, but shows where you should be putting `dispatch_async` call:

``` swift
    // Create a `NSURLSession` object
    let session = NSURLSession.sharedSession()

    // Create a task for the session object to complete
    let task = session.dataTaskWithURL(url, completionHandler: { (data, response, error) -> Void in
         // Process the `data`
         // Convert `data` to JSON
         // Update the array the table will show
          // Tell the table to reload on the main thread
         dispatch_async(dispatch_get_main_queue()) { [unowned self] in
             self.tableView.reloadData()
         }
    })

    // Start the downloading.  NSURLSession objects are created in the paused
    // state, so to start it we need to tell it to *resume*
    task.resume()


```

**Comment by ghost** [comment]
The source of the problem is that there is no guarantee that the thread has received the data from the main request if the NSURLSession is asynchronous, so even with a call to dispatch_async, other calls fail because they proceed in parallel before the network request has completed.

The only method that seems logical is to spin until the network request has completed. That's harmful, but I've tried with dispatch_barrier and dispatch_sync. Neither resolve the issue; it's deadlock city.

**Comment by ghost** [comment]
My implementation is similar but there's a ton of singleton abstraction and stuff that obscures things:

1) UITableViewController calls dataSource method to update data in the model. Procedurally, a dispatch_async() to reloadData() follows this.
2) DataSource requests data from singleton [This is where the error is: the data processing method is returning before the data can actually be processed.]
3) Singleton caches last data, passes it to DataSource on refresh.

It still does not complete correctly; I have tried the above implementation.

**Comment by danakatz** [comment]
@manglano Instead of thinking about when the singleton's data task returns, which is not something you can predict or control, think about what the networking call does _once it has the data_ -- whenever that may be. For example, in `func issuesRequestion(urlString: String, completion:([[String: AnyObject]]?) -> Void)` from the networking code in the [assignment 4 write-up](http://uchicago.mobi/sessions/session4/), you'll see that in line 121 it calls `completion(issues)`. From the calling controller, you can pass in a `completion` function that takes those retrieved issues as an argument and then, inside that `completion` function, make any other calls that depend on having the data from the API.

**Comment by ghost** [comment]
Okay, but we've compartmentalized everything because of singletons & MVC, so I can't access the necessary method calls from the singleton in which the networking call is occurring.

I've specified completion blocks for the dataSource method which calls the singleton method. The completion blocks do not resolve the issue.

I would really appreciate some code demonstrating how exactly this should be implemented or an explanation in class, because:
1) It's essential functionality for a good app which uses the network interface.
2) I feel like I'm getting dinged for the same thing twice without an adequate explanation of how to resolve it.
3) I have spent a lot of independent time trying to understand the issue to no avail. 

Thanks.
