### ISSUE TITLE
Adpative Cell Height Ambiguous 

### ISSUE THREAD

**Issue by lw334** [uchicago-mobi/2016-Winter-Forum#177]
I sat the margin constraints for the cells, then story complains about "height is ambiguous for "title"". After I sat the height constraint, the storyboard complains about "Vertical position is ambiguous for "title". Am I missing a step? Is there other constraints I should sat? Thanks! 

To add on this, for setting the positions for the favorite star, I get a warniing saying the frame for it will be different at run time: position/size will be different at run time but is ... in the canvas. Is this something I can ignore? If not how can I solve this? Thanks!

**Comment by tabinks** [comment]
This means that you are missing some constraints.  It is unable determine the height based on the constraints you have.  Unfortunately, you just have to play around with it a bit to debug.  In some cases, I find it easier to remove all the constraints and then add them back.

> To add on this, for setting the positions for the favorite star, I get a warniing saying the frame for it will be different at run time: position/size will be different at run time but is ... in the canvas. Is this something I can ignore? If not how can I solve this? Thanks!

You just to need to update the frame.  Look under "Editor > Resolve Auto Layout Issues > " and select update frame.

**Comment by lw334** [comment]
So I display 3 items (title-date-content) in each cell in the master view, I think storyboard is complaining about not knowing the heights so it can't automatically calculate the cell height. I specified 2 cell heights and it stopped complaining. But then I lost the auto cell height for the title because I need to at least specify 2 heights to help storyboard calculate the cell height from bottom to the top.. Not sure.
