### ISSUE TITLE
fatal: Unknown index entry format 642e0000

### ISSUE THREAD

**Issue by lw334** [uchicago-mobi/2016-Winter-Forum#179]
Yeah.. Added a few lines and I'm getting this error. Anyone has any idea why this might be the case? Thanks!

**Comment by ghost** [comment]
Is this with NSUserDefaults? Just discovered that NSUserDefaults is extremely picky about its formats, due to serialization...gotta refactor a big chunk of code, now: http://stackoverflow.com/questions/19720611/attempt-to-set-a-non-property-list-object-as-an-nsuserdefaults

**Comment by lw334** [comment]
It comes from git.
