### ISSUE TITLE
Important Notes for Assignments

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#18]
- You will be graded on the 'master' branch of your repository only.  You can create as many branches as you want, but the only one that will be graded is master.
- Your git commit messages should be informative.  Here is a posit that shows some good examples: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message.   You should be committing very often as you work.  Every time you do something meaningful (new feature, fix bug, add comments), commit it.  This is an important part of _best practices_ in software engineering...which we will be taking into account when grading assignments.
- Your README file should contain some basic information about the repository.  At the bare minimum, include your name and the assignment number.  Also, use the README to cite sources you used going forward.  **This is in addition to including sources, links, references in your code where it applies**.  The README citations is a summary of what we will find in the code.

**Comment by vhicks** [comment]
Hi prof @tabinks - I am a Git novice and created some errors trying to load my project to the master repo. I was only able to figure out a branch for this first assignment. In my README I informed the graders of the homework branch. Since this message was just posted can it suffice for the first assignment.

I have got a handle on it now. Thank you,
Veronica

**Comment by tabinks** [comment]
@vhicks This is fine.  

For everyone else, if you ever have problems with git, do not fret about it too much.  We will get it resolved.  Remember that you git history log will show us when you committed your work.  We can just look to verify you had the assignment done in time, regardless if it made it to github or not.  So always make sure to make your final commits before the deadline.

**Comment by lw334** [comment]
for assignment 2 should we create a separte repo or just work within the one we got last week? I didn't get a link that will create another private repo for me this week. Thanks!

**Comment by danakatz** [comment]
@lw334 Yes, every assignment will have its own repo. You can find the link to create one for assignment 2 in this issue: https://github.com/uchicago-mobi/2016-Winter-Forum/issues/15
