### ISSUE TITLE
Get out of editing mode

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#180]
In a TableViewController, the edit button turns into a done button so the user can click done to exit editing mode. In the BookmarkViewController, my edit button doesn't turn into a done button automatically, and I've tried to programmatically change its behavior by implementing an editPressed function that checks if the table view is being edited and changes the title of the button to "Done", but that doesn't do anything. 

Should the behavior of the edit button automatically change? If not, is there a method I'm supposed to implement?

**Comment by tabinks** [comment]
If you are not using the built-in edit button from a table view controller then you will be required to manage the state of the text in the button.   Take a look at the is selected property on the button. One possible way to address this would be to set up a property observe her and if the button is selected change the text to done. If the button is not selected change the button to edit.

**Comment by aaizuss** [comment]
@tabinks Ok - that sounds like what I was originally trying to do in my editPressed function. I've looked at the documentation for UIBarButtonItem, and I didn't see an is selected property...
