### ISSUE TITLE
Office Hours This Week

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#183]
I will not be holding office hours on Thursday this week.  Instead, I will hold them Monday before/after class.

**Comment by danakatz** [comment]
I'll also be moving my Thursday office hours to Saturday in Hyde Park (details to follow later in the week).

**Comment by susanstevens** [comment]
My office hours will be on Sunday from 4-6pm in CSIL 1 in Crerar.

**Comment by msylvester** [comment]
@danakatz or @susanstevens, can either of you help me with API calls? 

I need to make one for my final project and I am struggling with it.

**Comment by susanstevens** [comment]
@msylvester Yes!  What API are you using?

**Comment by msylvester** [comment]
@susanstevens it Arts-y (https://developers.artsy.net)

I'll come to office hours on sunday

**Comment by bobby-digital-23** [comment]
Thursday 4-5pm and 8:30-10:30pm CSIL

Further details posted here:
https://github.com/uchicago-mobi/2016-Winter-Forum/issues/184
