### ISSUE TITLE
Office Hours - Thursday @ 4-5pm AND 8:30-10:30pm CSIL

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2016-Winter-Forum#184]
Please let me know if you plan on coming to either/both office hours on Thursday. I specifically scheduled the evening office hours after evening classes.

![git](https://cloud.githubusercontent.com/assets/10453834/13309310/44b297f4-db41-11e5-813a-130f94053627.png)

[http://xkcd.com/1597/](http://xkcd.com/1597/)

**Comment by hbennett766** [comment]
I'll be at the 4pm session, hope you're feeling better!!

**Comment by cjhodnefield** [comment]
I'll be there for the later time this evening.

**Comment by Eric-Warehime** [comment]
I'll be at the late night hours.

**Comment by bobby-digital-23** [comment]
Thanks for the replies everyone. 

Hannah, I'll be there in a few min.
