### ISSUE TITLE
Artsy API

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2016-Winter-Forum#185]
@msylvester 
Mike, I'm posting this here so it doesn't muddle the office hours thread.

In terms of [Artsy](https://developers.artsy.net), have you checked the iOS projects the Artsy team and other developers have posted to GitHub?
https://github.com/artsy

[Eigen](https://github.com/artsy/eigen) and [Eidolon](https://github.com/artsy/eidolon) work nicely and look slick! Eigen in particular seems like it could be very helpful in terms of exploring the Artsy API. Check it out and even build it in Xcode if you get the chance.

Hint: If you want to build those projects in Xcode, you might want to first [update the version of Ruby](https://coderwall.com/p/4imsra/upgrading-ruby-to-2-1-0-and-above-in-mavericks) and install and/or upgrade [CocoaPods](https://cocoapods.org) and [Bundler](http://bundler.io) on your Mac **BEFORE** you follow their installation instructions. Typing in the 4-5 command line instructions they list actually does create a working Xcode project **IF** you update/install those three things I just mentioned on your Mac first (wish they made this a little bit clearer in their instructions!). 😉 

If you need help with any of this, please stop by office hours!

**Comment by msylvester** [comment]
wow. really cool.  I will be at your office hours tonight the late one.
