### ISSUE TITLE
Toolbar overlaps iOS status bar

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#187]
I have this situation:

<img width="584" alt="screen shot 2016-02-28 at 11 56 50 am" src="https://cloud.githubusercontent.com/assets/6961916/13380911/89e5bd36-de13-11e5-97ba-40c588232c1b.png">

The navigation bar was positioned within a table view in the Storyboard. Any way to resolve it do I need to tear it down and redo programmatically? Most of the StackOverflow answers I found were outdated (iOS 7).

**Comment by susanstevens** [comment]
How did you add the navigation bar?  Did you do Editor > Embed In > Navigation Controller from Storyboard?  This usually works better than dragging and dropping a navigation bar into a view controller.

**Comment by ghost** [comment]
I did a drag-and-drop. Embedding solved the problem. Thanks, Susan!
