### ISSUE TITLE
Reminder: Office Hours Today 4-6pm

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Winter-Forum#188]
See you in CSIL 1 in Crear!  If you have questions about something specific to your final project, feel free to post them here beforehand.

**Comment by lw334** [comment]
I want my users be able to register, store information, and communicate each other within the app...I looked at Parse but it's retired and doesn't allow registering new account at this point. I wasn't able to find useful projects built with CloudKit. Is there a way to administer or mock the functionalities? Thanks!

**Comment by susanstevens** [comment]
@lw334 We can look at some possibilities!

FYI, I may be 10 or 15 minutes late today, but I'm on my way.
