### ISSUE TITLE
CloudKit Tutorials

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Winter-Forum#194]
@lw334 and anyone else interested in using CloudKit in your final project.  Here are a couple good CloudKit tutorials written in Swift.  They're on the longer side, I know, but if you pick one and work through it step-by-step it should give you all the info you need start using CloudKit in your app.  If you get stuck, post here or bring questions to office hours!

http://www.raywenderlich.com/83116/beginning-cloudkit-tutorial (I remember using this last spring, and I found it helpful.)

http://www.appcoda.com/cloudkit-introduction-tutorial/ (I haven't worked through this one, but it's a bit more recent than the Ray Wenderlich tutorial.)

**Comment by lw334** [comment]
I'm asked to enroll in the apple developer program in order to use iCloud feature....I'm not sure how much I want to do that..Is there a way to get round this?

**Comment by lw334** [comment]
@susanstevens  :)

**Comment by tabinks** [comment]
@uchicago-mobi/mpcs51030-2016-winter 
I'm looking into this now.  There seems to be a change to the way that student developer accounts are handled in regard to accessing services.  I think it may be possible to access CloudKit without a paid developer account.  I have an email into Apple about it now.

If you are planning on using CloudKit and do not have a paid developer account, please respond here so I can get a count.

**Comment by lw334** [comment]
@tabinks  Hello Andrew. Did you hear anything back from Apple? If I plan to take the advanced class, would you say that I should just go ahead and get a developer acct?.....Thanks!

**Comment by tabinks** [comment]
I didn't hear back yet.  I would recommend you get a developer account.  You'll be putting apps in the store in no time. @lw334
