### ISSUE TITLE
Making projects public

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#199]
Are we free to make projects from earlier in the quarter publicly-available repositories?

**Comment by tabinks** [comment]
During the course you are not allowed to post anything publicly.  After the quarter, you should consult the Academic Integrity policy to make sure that you will not be violation.  There are specific guidelines on making previous coursework publicly available.  The policies are rigorously enforced.

This was discussed in #10 at the beginning of the quarter.
