### ISSUE TITLE
Case Studies

### ISSUE THREAD

**Issue by nicholasfasolt** [uchicago-mobi/2016-Winter-Forum#20]
By when should we have an app chosen for our case study, and will there be a schedule for when who will be presenting, or should they all just be done by a certain date and then chosen at random each class?

Thanks!

**Comment by tabinks** [comment]
There will be a sign-up sheet and schedule so you will know when you are going.  I'll put it together today and send it out.

**Comment by tabinks** [comment]
@nicholasfasolt It's up...first come, first serve.
