### ISSUE TITLE
Assignment 7 Feedback

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#208]
Has anyone received a grade for assignment 7? I'm obviously not in any rush but it's been nearly two weeks, so I wanted to make sure I'm not the only one who hasn't gotten feedback yet.

**Comment by susanstevens** [comment]
@aaizuss Sorry for the wait!  These assignments have taken us a little longer to grade.  Some grades have been posted, and the rest should be up soon.

**Comment by aaizuss** [comment]
ok, good to know; thanks!
