### ISSUE TITLE
Animating Views in a Playground

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Winter-Forum#209]
I got a question in office hours about animating views in a playground.  Here's a good blog post about it: http://www.techotopia.com/index.php/An_Introduction_to_Xcode_7_Playgrounds.

**Comment by joshuacalloway** [comment]
Do you think it works with "xcrun swift  someProgram.swift"  ?    

Playground seems to be slow too, so looking for a faster way to throw up UIs

**Comment by susanstevens** [comment]
@joshuacalloway Not quite sure what you mean by this.  Did you get it working?  If playground is slow, you can also open a new project and test things in simulator or on a device.
