### ISSUE TITLE
A Couple of Notes about Class on Monday

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#221]
Remember that your projects are due Wednesday next week, not Monday.  On Monday, you should come prepared to talk about your app, show a couple of slides, or do a live demo.  You can do a demo using your app in the simulator if you would like.  You app does not need to be finished to show it off in class.  You can choose to highlight a single feature to show if you are still not done with everything.  This is just a chance for you to show off your hard work.

I will come to class early and stay late if anyone needs some assistance finishing up any last minute features.

Also, don't forget about the written part of the projects.  They take a little bit of time, but are an important part of the project.

**Comment by tabinks** [comment]
For those that asked, I won't be at class too early, maybe 15 minutes or so, but I will stay as late as needed.

**Comment by ghost** [comment]
How many minutes should our presentation take?

**Comment by tabinks** [comment]
@manglano  It should be about 5-10 minutes.  We'll open it up for questions after each presentation.
