### ISSUE TITLE
Splash Screen Requirement

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#225]
Can you explain what exactly the requirement is for the splash screen? You say not to use storyboard, and every method I've found involves storyboard. I also thought about putting a view over my view controller that only displays an image when the app first loads, but that seems dumb because that would mean making the user wait longer to use the app. Isn't the point of a launch image to make the user think your app is loading fast?

**Comment by tabinks** [comment]
@aaizuss The requirement is to show some sort of view when the app launches. There are many different ways to do this, the simplest is to show an entire screen `UIView` in `viewWillAppear` and then make it disappear either from a touch or timer.  

I did not want you to think that the LaunchScreen.storyboard file (which is included in every Xcode project) counted as this splash screen.  This is only shown from a new application launch not from when the application will become active after being suspended.  

> I also thought about putting a view over my view controller that only displays an image when the app first loads, but that seems dumb because that would mean making the user wait longer to use the app.

It all depends on what you show.  Yes, if you are just trying to launch you app super fast, it may seem counterintuitive (or more technically, dumb), but there are many other reasons you may want to show something before users are taken into the app:
- A login screen.  Dropbox does this.
- An onboarding flow for information about new features.  Google does this in their apps that have new features.
- Branding.  You may want to flash your logo to subconsciously reinforce how important you company is in their daily life.  Twitter does this.  
- A distraction.  If new data is being downloaded when the user navigates back to your app it may be better to show them a splash screen than an empty screen.

The days of slow launches are over (and enforced by the watchdog system feature).  Instead, you should focus on the splash screen as another opportunity to inform, misdirect, or delight your users.  The splash screen does not have to be visible for a long time....just a splash.

**Comment by aaizuss** [comment]
Okay, thanks for clarifying! Would it be redundant to use LaunchScreen.storyboard to make a lunch image (different from what my splash screen will show) in addition to a splash screen? I wanted to use a very simple launch image based on the [Human Interface Guidelines for Launch Files](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LaunchImages.html)

**Comment by lw334** [comment]
@aaizuss  actually have the same question. @tabinks should I show the splash screen each time the user goes back to home and then reopen the app? I'm confused about what you said about using it to show a login and onboard the user. If that's the case, there is no need to use this kind of splash screen each time you open it and just a logo would be fine?
