### ISSUE TITLE
Splash screen playground

### ISSUE THREAD

**Issue by msylvester** [uchicago-mobi/2016-Winter-Forum#227]
@tabinks can you please put the playground file that we went over yesterday for adding the splash screen in the witner-playground folder? I didn't see it there.

**Comment by tabinks** [comment]
@msylvester Done.  It's called 2016-DoNotTry.

**Comment by lw334** [comment]
@tabinks  the code compiles but throw a nil error. Is that why it's called DoNotTry? ........
