### ISSUE TITLE
Relative positioning of subview elements

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#26]
When positioning subview elements programmatically, are coordinates relative to a global plane, or to the upper-right corner of the parent view (superview?)? The superview is definitely positioned on a global plane but there's some errors in positioning the subviews when I make the assumption that the subviews are positioned on the same coordinate system.

Is there a guide to the layout logic for iOS? Some cursory searching hasn't uncovered one.

Thanks!

**Comment by danakatz** [comment]
@manglano Subviews are positioned relative to their superview, and the origin is actually the top _left_ corner. Here's a helpful [overview](https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/ViewPG_iPhoneOS/WindowsandViews/WindowsandViews.html) of view and window architecture from the iOS developer library -- check out the section called **View Geometry and Coordinate Systems** for an explanation of `frame`, `bounds`, and `center` that I think will clarify things for you!

**Comment by ghost** [comment]
Thanks!
