### ISSUE TITLE
Button Bug: Tag isn't changing

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#27]
I'm having an issue with displaying the information for the correct animal. The button titles are correct, but the alert and label always show the information for the last animal in the scroll view. I figured out that the button tag isn't changing (it's always 2, so that's why the app always shows info for the last animal), but I don't know how to set the tag so that it changes. 

Currently, I create each button in a for loop in viewDidLoad, and I also set the tag in that loop. To make sure = button.tag is accessible in other methods, I initially declare the button variable globally. Then I declare it again in the for loop before setting its properties (it's weird and repetitive but whenever I try to change it something breaks), so that might be part of the issue... It doesn't make sense to me why the button titles change as I scroll, but the tag says the same. Any ideas?

![before press](https://cloud.githubusercontent.com/assets/11274851/12374029/bbdecfca-bc54-11e5-8d98-45918c42db69.png)
![pressed](https://cloud.githubusercontent.com/assets/11274851/12374030/c3c96646-bc54-11e5-9536-f961f903114b.png)

**Comment by danakatz** [comment]
@aaizuss I'm not quite sure I understand how you're declaring the buttons. Do you have 3 button instance variables that you then set in the for loop? 

Instead of trying to make the tag change, I would set it up so that you can declare 3 buttons with the right tags that never have to be reset. Also, I noticed that while the button title is correct in your screenshots, the label is not -- could that be part of the problem? Maybe the button is displaying the polar bear info for the same reason the label says 'Polar Bear'.

**Comment by ghost** [comment]
Corollary to this, how do we detect the button presses? I implement a method called buttonTapped with a placeholder that outputs "Button pressed" to the console, but there's some missing connection in the background. 

Logically, there's some action that needs to be plugged into the switchboard that says "okay, instance of button pressed -> execute some code with access to button instance variables" but some exhaustive searching hasn't illuminated me. All I find is methods to connect from the storyboard to the ViewController, but the buttons aren't in the storyboard--I cannot connect them.

**Comment by aaizuss** [comment]
@danakatz I know about the label issue, and it's definitely for the same reason because it depends on the button tag. 

As for how I'm declaring the buttons, I declare a button called button globally, and then in the for loop, I use that same code again. Since that happens in the for loop, that should create 3 instance variables, right? Maybe the issue is I'm really only making one button, and the button's title and location changes when I scroll, but the button itself has the properties that were most recently set (which is why the tag is always 2).

**Comment by danakatz** [comment]
@aaizuss that sounds like a definite possibility. Global variables can be accessed from inside methods, but they can't be declared there -- you have to declare them at the class level, so it makes sense that your global variable will always reference the last button in the loop. 

Having three button properties of your class is one design option for this assignment, but there are other ways to access UIViews without storing them in instance variables. You might find the [viewWithTag(_:)](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIView_Class/#//apple_ref/occ/instm/UIView/viewWithTag:) method helpful if you'd rather declare the buttons in your for loop and then save them somewhere you will still be able to access them, like attached to a view that _does_ have a global reference.

@manglano there are numerous tutorials available about adding UIButtons programmatically in Swift that I think will help you. I'll also direct you to the documentation for the [addTarget(_:action:forControlEvents:)](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIControl_Class/#//apple_ref/occ/instm/UIControl/addTarget:action:forControlEvents:) method. In the discussion, you'll see the note that "The action message may optionally include the sender and the event as parameters, in that order."
