### ISSUE TITLE
ScrollView doesn't scroll content.

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#28]
I create a UIScrollView in storyboard and link it to ViewController.swift, with the usual boilerplate provided by the IDE. Subviews instantiated programmatically--that part must work, because images display within the scrollview. scrollEnabled & pagingEnabled set to true. contentSize set to size of an Image. ViewController.swift is designated as UIScrollViewDelegate. The ScrollView's delegate is set to 'self' within the ViewController class.

The scroll view does not scroll. Why?

**Comment by cjhodnefield** [comment]
I believe you want to set your contentSize to 1125x500. I'm not 100% sure if this justification is correct, but I think when you set the content size to the size of an image, the scrollView doesn't think there is any more content to scroll to, and so it doesn't let you scroll. I was having a similar problem for a while.

Again, not sure if my justification is correct, but I know that once I changed my contentSize to 1125x500 (programmatically) and made sure frame size was 375x500, it worked for me.

**Comment by ghost** [comment]
It was that and the frame--I was not even aware that specifying the frame size was a necessary step!

**Comment by susanstevens** [comment]
@manglano Glad you were able to figure this out!  As @cjhodnefield suggested, `contentSize` tells the scroll view how much to scroll, and `frame` tells the scrollview how much content should be visible at one time.  Whenever you drag and drop a visual element like a scrollview into your storyboard, the size and placement it has there determines it's initial frame.  As explained in the assignment notes, unlike `frame`, which can be set in storyboard or programmatically,  `contentSize` can only be set programmatically (not in storyboard).
