### ISSUE TITLE
Help with audio files

### ISSUE THREAD

**Issue by cjhodnefield** [uchicago-mobi/2016-Winter-Forum#29]
Are there any good resources that explain how to get sound files working in an Xcode project? I haven't been able to find anything very easily, and I also haven't been able to successfully import several different formats of sound files into my project (though I might be doing it incorrectly or something). Any help (or links to useful documentation) would be appreciated.

**Comment by susanstevens** [comment]
@cjhodnefield Did you take a look at the last tutorial listed at the top of the assignment page?

**Comment by cjhodnefield** [comment]
@susanstevens Oh, I hadn't made it through all of those tutorials yet, but that one looks like it will probably have what I'm looking for. Thanks!

**Comment by susanstevens** [comment]
@cjhodnefield No problem! :+1:
