### ISSUE TITLE
Assignment-1 Repo Link

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#3]
Click on this link and a private repo will be created for your first assignment:
https://classroom.github.com/assignment-invitations/4ae294be26a8ecfe5588e9f82f71f4e8

If you have any issues, please post them below.

**Comment by arcastar13** [comment]
I don't know if it's just me but the link doesn't work :/

**Comment by songty11** [comment]
Hi, I deleted the repo by mistake...in "settings->Repositories->Leave".... And now I can't get in my repo. I tried to recreate the repo by clicking the url above, but only to the get the info "page not found"...Could you please tell me what I should do to create a new "assignment-1 repo"? thx~

**Comment by susanstevens** [comment]
@songty11 It looks like your repository is still there, but you may have removed your access to it.  What happens if you go to this url: https://github.com/uchicago-mobi/assignment-1-songty11?  If you're unable to get to your repo with that link, @tabinks might need to re-enable your access.

**Comment by songty11** [comment]
@susanstevens Thanks for your help, I still can't get in. After I entered the url you gave, there would be a picture saying ---- 404,This is not the page you are looking for.

**Comment by tabinks** [comment]
@songty11 I see it as well, with you being the only contributor.  https://github.com/uchicago-mobi/assignment-1-songty11

If all else fails, what happens when you reclick the link above?

**Comment by songty11** [comment]
@tabinks it will create this link-- https://github.com/uchicago-mobi/assignment-1-songty11
which I can't get in ..orz..

**Comment by stian11** [comment]
@tabinks Hello, This is songty11, I recreated a new account to submit iOS homework

**Comment by bobby-digital-23** [comment]
@stian11 Did you resolve your issue? Looks like you have a new repo. Can you access it?
https://github.com/uchicago-mobi/assignment-1-stian11

**Comment by stian11** [comment]
@bobby-digital-23 Yes! Everything works fine! Thanks for your help!
