### ISSUE TITLE
Build succeed but app can't launch

### ISSUE THREAD

**Issue by lw334** [uchicago-mobi/2016-Winter-Forum#30]
This is the stack trace:
2016-01-17 13:52:05.259 It's A Zoo in There[20644:900986] **\* Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<It_s_A_Zoo_in_There.ViewController 0x7fd2f8eb4590> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key scroll.'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010cc94e65 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010e9d4deb objc_exception_throw + 48
    2   CoreFoundation                      0x000000010cc94aa9 -[NSException raise] + 9
    3   Foundation                          0x000000010d05d9bb -[NSObject(NSKeyValueCoding) setValue:forKey:] + 288
    4   UIKit                               0x000000010d640320 -[UIViewController setValue:forKey:] + 88
    5   UIKit                               0x000000010d86ef41 -[UIRuntimeOutletConnection connect] + 109
    6   CoreFoundation                      0x000000010cbd54a0 -[NSArray makeObjectsPerformSelector:] + 224
    7   UIKit                               0x000000010d86d924 -[UINib instantiateWithOwner:options:] + 1864
    8   UIKit                               0x000000010d646eea -[UIViewController _loadViewFromNibNamed:bundle:] + 381
    9   UIKit                               0x000000010d647816 -[UIViewController loadView] + 178
    10  UIKit                               0x000000010d647b74 -[UIViewController loadViewIfRequired] + 138
    11  UIKit                               0x000000010d6482e7 -[UIViewController view] + 27
    12  UIKit                               0x000000010d51eab0 -[UIWindow addRootViewControllerViewIfPossible] + 61
    13  UIKit                               0x000000010d51f199 -[UIWindow _setHidden:forced:] + 282
    14  UIKit                               0x000000010d530c2e -[UIWindow makeKeyAndVisible] + 42
    15  UIKit                               0x000000010d4a9663 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4131
    16  UIKit                               0x000000010d4afcc6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1760
    17  UIKit                               0x000000010d4ace7b -[UIApplication workspaceDidEndTransaction:] + 188
    18  FrontBoardServices                  0x00000001108c3754 -[FBSSerialQueue _performNext] + 192
    19  FrontBoardServices                  0x00000001108c3ac2 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
    20  CoreFoundation                      0x000000010cbc0a31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
    21  CoreFoundation                      0x000000010cbb695c __CFRunLoopDoSources0 + 556
    22  CoreFoundation                      0x000000010cbb5e13 __CFRunLoopRun + 867
    23  CoreFoundation                      0x000000010cbb5828 CFRunLoopRunSpecific + 488
    24  UIKit                               0x000000010d4ac7cd -[UIApplication _run] + 402
    25  UIKit                               0x000000010d4b1610 UIApplicationMain + 171
    26  It's A Zoo in There                 0x000000010cab17bd main + 109
    27  libdyld.dylib                       0x000000010f53792d start + 1
    28  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Not sure how to interpret this error and some general tips on debugging swift would be appreciated. Thank you!

**Comment by lw334** [comment]
Ok... I figured out. Make sure you delete any failed declaration of properties of the UI elements in the view controller. So it's not referred as multiple things and some of the keys you never use.

**Comment by susanstevens** [comment]
@lw334 Good catch!  The error you were getting, "this class is not key value coding-compliant for the key ___", is often a sign of IBOutlets not being hooked up correctly.  (Not that the wording of the error makes that especially clear...)
