### ISSUE TITLE
The scroll view won't scroll

### ISSUE THREAD

**Issue by nickpann** [uchicago-mobi/2016-Winter-Forum#31]
I am having a really hard time getting the scrollview to scroll. Referring to this step: "Make your ViewController conform to the UIScrollViewDelegate protocol... You will need to set your scrollview's delegate property appropriately. This can be done programmatically or in Storyboard." 

Things I've done:
- Made ViewController conform to the UIScrollViewDelegate property.
- Set the scrollview's delegate property accordingly in storyboard (confirmed by printing scrollview.delegate to the terminal).
- Set content size appropriately (1125 x 500).
- Auto layout is off.

I've read through several tutorials and can't identify what I missed. I'd greatly appreciate any advice.

**Comment by ghost** [comment]
Hey Nick, is your ScrollView's frame set to the size of a slide (375 x 500)? This was a setting I was missing and now my view is scrolling (oddly, it wasn't in the Wenderlich tutorial but is necessary for our app).

**Comment by lw334** [comment]
That was precisely the problem for me. Thanks @manglano !

**Comment by nickpann** [comment]
David, thanks for the suggestion. Although it's still not scrolling, that was a problem. I wasn't understanding the distinction between the frame and content size. When I printed both to the terminal, my frame was set to 1125x500, and my content size was 0x0. This it makes sense why the directions say content size can only be changed programmatically, but you can resize the scrollview in the interface builder (that changes the frame size, not the content size).

**Comment by susanstevens** [comment]
@nickpann If you're able to come to office hours, I can take a look at your code with you.  It sounds like you're on the right track, but it's hard to say exactly what the problem is without looking at your project.

Definitely make sure `contentSize` and `frame` are set correctly (`contentSize` should be 1125x500 and `frame` should be 375x500).  Sounds like you have that figured out, though.  You might also want to make sure you don't have the property `userInteractionEnabled` set to false.  You can toggle this property in storyboard or programmatically.

**Comment by nickpann** [comment]
@susanstevens I will come to the office hours. Will you be in the Crerar lab? The course website just says "Hyde Park".

**Comment by bobby-digital-23** [comment]
Are you programmatically adding your buttons and your images via the `-addSubview:` method?

Have you seen the following Apple docs? 

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/UIScrollView.html#//apple_ref/doc/uid/TP40012857-UIScrollView

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIScrollView_Class/index.html#//apple_ref/occ/cl/UIScrollView

Dana also inlcuded a link to Apple's "View Programming Guide for iOS" in issue #26 but just in case you didn't see that, it is a guide that is definitely worth reading:

https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/ViewPG_iPhoneOS/WindowsandViews/WindowsandViews.html

**Comment by nickpann** [comment]
It's working now.

**Comment by bobby-digital-23** [comment]
@nickpann What resolved the issue?

@manglano Which raywenderlich.com tutorial were you referring to? This one?
http://www.raywenderlich.com/76436/use-uiscrollview-scroll-zoom-content-swift

I ask because it helps identify those resources which are helpful and those which are not. Thanks

**Comment by nickpann** [comment]
I think it was actually David's advice that resolved the issue. I came to office hours and tested it again, and it was scrolling.

I had followed all of the other directions: programmatically adding instructions, etc. I think the only thing the instructions didn't capture was the frame/content size distinction.

**Comment by bobby-digital-23** [comment]
@nickpann Glad to hear you got it working Nick!

The following short post nicely explains how frame and content size work with scrollviews and it should hopefully clear up any confusion. If anyone finds this helpful (or not), please say so. :-)
https://www.objc.io/issues/3-views/scroll-view/
