### ISSUE TITLE
Office Hours Today 4-6 in CSIL 1

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Winter-Forum#32]

**Comment by cnfshandson** [comment]
Hi Susan,

Do I need to find the pictures and sound files myself or they are already provided somewhere?  Thank you

**Comment by susanstevens** [comment]
@cnfshandson No pictures or sound files provided.  Find your favorites on The Google.

**Comment by cnfshandson** [comment]
Got it, Thanks.
