### ISSUE TITLE
github: commit is not possible because you have unmerged files.

### ISSUE THREAD

**Issue by brittneyli** [uchicago-mobi/2016-Winter-Forum#34]
I'm still having some trouble with pushing to github...

I created the assignment2 repository last week and tried to push my project(the entire folder) to it and failed. Looks like this: 
![screen shot 2016-01-18 at 11 50 44 am](https://cloud.githubusercontent.com/assets/9668946/12398513/bd39643a-bdd9-11e5-852f-f96bc8f69e76.png)

So I fumbled around a bit and accidentally used the git reset --hard command which caused me to lose my entire project. So I deleted the entire old xcode project and started a new one, but now I'm finished I can't push it to the repository. It always says that "commit is not possible because you have unmerged files." I looked up some answers on StackOverflow but I'm nervous to try out the commands in case I lose everything again... any help please?

**Comment by tabinks** [comment]
it looks like you have nested git repos.  We can get it sorted out in office hours or class.  In the meantime, can you just share it to me via google drive?

**Comment by brittneyli** [comment]
That would be great, thanks! I'll send the link via email.
