### ISSUE TITLE
Built and ran but with error message

### ISSUE THREAD

**Issue by chuanxix** [uchicago-mobi/2016-Winter-Forum#35]
My app can show up and run in the Simulator. However, sometimes(not every time that it's simulated) when the button is clicked. It takes like 2 seconds for the sound to play and an error message would show up in the console. It says: ERROR 181: timed out after 0.012s (228 229);  mMajorChangePending = 0

The app can still run properly after the error message shows up. No more error message would show up after clicking more buttons in the Simulator.

I googled but still don't have any clue how this happened.

**Comment by chuanxix** [comment]
I took the dispatch_sync approach mentioned here: http://www.btday.com/avaudioplayer-problems-with-swift-2-0/
and the error message doesn't show up any more.

**Comment by tabinks** [comment]
There are different ways of playing sounds depending on the desired behavior.  We'll go over these later.  A big factor, unfortunately, is the format of the sound file.  iOS can be picky about this and not present good debugging information about it. 

The `dispatch_async` in this snippet is just ensuring that the enclosed method plays on the main thread

``` swift
dispatch_async(dispatch_get_main_queue(), {
                        (self.playRocketExplosionSound("Bang.mp3")
                        })
```

In iOS, the main thread is responsible for all user interactions.  If you try doing something UI related on another thread it may not fail, but you won't be able to see/hear the output.  Again, this can be tricky to debug.
