### ISSUE TITLE
Evening Office Hours

### ISSUE THREAD

**Issue by nicholasfasolt** [uchicago-mobi/2016-Winter-Forum#36]
Hi there!

Would it be possible to adjust the office hours so that there is another evening session during the week sometime? The only time I am currently able to attend is the Sunday session (I have class Tuesday evenings and am at work during all of the other day time sessions), which is cutting it a bit close with the due date of the homework if there is a bigger issue I need help with.

**Comment by bobby-digital-23** [comment]
Hi Nicholas, what days/times work for you? Can you meet after 6pm on Thursdays?

**Comment by tabinks** [comment]
Yes, please leave some times that you would be available.

**Comment by nicholasfasolt** [comment]
Sorry about that - should have posted some from the get-go!

Thursdays after 6 works great, as do Wednesdays or Fridays (though Thursdays seem like they'd be best (on campus or off). Saturday any time after 2PM is good as well.

**Comment by bobby-digital-23** [comment]
Does anyone else have time conflicts with the currently scheduled office hours? If so, please let us know ASAP. 

@nicholasfasolt
I have prior plans for this Thursday evening (Jan 21st) but I should be available next Thursday evening (Jan 28th). 

How late could you meet on Thursdays? Some students have classes on Thursdays from 5:30-8:30pm. I'd like them to have the opportunity to join us also. :-)

**Comment by nicholasfasolt** [comment]
@bobby-digital-23 no worries about this week.I work until 5:30 and am available any time after that Thursdays. I'm totally OK with later, as late as necessary, so that folks with Thursday class can attend as well.

**Comment by msylvester** [comment]
@bobby-digital-23 thanks for the thread.  Tuesday-Thursday early evenings do not work for me since I have class. 

However, after 8:30 on those days I am available.  Friday I am open all day.  

Can you consider keeping Thursday afternoon office hours since those are a good opportunity to get started on the project before the weekend (if you don't move them to Fri)?

**Comment by shuaib88** [comment]
@bobby-digital-23 Anytime Thursdays work for me, but Thursday later might be nice for those students that have class. 

I also remember you were saying your were considering switching your Monday afternoon time to Friday (to avoid that last minute push). Friday afternoon would be a great candidate if you had that availability.

**Comment by bobby-digital-23** [comment]
Anyone else?

Thanks to everyone who has posted. I'm fine with all of the suggested times and indeed, Monday office hours can be stressful, for everybody, at times. :-) 

Let's briefly take a poll in class tonight (for those who are not seeing the forum posts, which we'll also address) and then we will rearrange office hours, if needed, to the days/times which work best.

**Comment by nicholasfasolt** [comment]
I've changed my schedule and am now able to attend office hours on Tuesday evening downtown. 

If it's somehow possible, it would still be great if we could have an evening session sometime for those who work 9-5, since the only sessions available for us is either right after class (Tuesday evenings) or right before class (Sunday afternoons), but for me this is more of a nice-to-have now than a need-to-have (at least for me). Thursday and Friday evenings, or Saturday afternoon/evenings would work.

**Comment by bobby-digital-23** [comment]
@nicholasfasolt 

We'll be sending out a survey soon to see which days/times work best for everyone. Hopefully everybody has their Github notifications turned on now per the Professor's suggestion last night.

Regardless, I should be able to meet with you, and whoever else would like to join, this Thursday evening at the very least. Will keep you posted and please fill out the survey. Thanks! :-)
