### ISSUE TITLE
Some Apple News (week 3)

### ISSUE THREAD

**Issue by nicholasfasolt** [uchicago-mobi/2016-Winter-Forum#38]
1/18/16 - [Apple Admits iOS 9.2 Has A New Problem (Forbes)](http://www.forbes.com/sites/gordonkelly/2016/01/18/apple-ios-9-2-iphone-battery-problem/#2715e4857a0b568e1f192622)

1/19/16 - [Apple Releases iOS 9.2.1 With Bug Fixes, Security Updates (MacRumors)](http://www.macrumors.com/2016/01/19/apple-releases-ios-9-2-1/)

**Comment by nicholasfasolt** [comment]
Tangentially related (I think) - about Apple's mobile advertising platform iAd.

1/15/16 - [What Apple's iAd changes mean for the industry (Digiday)](http://digiday.com/platforms/apples-iad-changes-mean-industry/)

**Comment by tabinks** [comment]
NFL advertises for iPads: 
http://appleinsider.com/articles/16/01/24/microsoft-surface-blamed-for-nfl-football-playoffs-meltdown-
