### ISSUE TITLE
RWDevcon Student Scholarship deadline extended!

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2016-Winter-Forum#40]
Former students who have attended this conference say it is very helpful for learning and networking but that it is quite expensive. The good news is that for the first time ever, Ray Wenderlich is offering FREE scholarships to this year's conference to university students, regardless of age. The application is simply to write an email explaining why you should attend! The deadline is tomorrow, Jan 20th, so don't wait too long if you're interested. Let us know if you win! :-)

http://www.raywenderlich.com/124247/rwdevcon-student-scholarships-deadline-extended

**Comment by yiqin** [comment]
I went to the conference last year. Some speakers are very famous in the iOS industry, including the engineer at Facebook who first implemented 3D touch to Instagram in iPhone 6s. Also, before this class, I learned tutorials written by Ray Wenderlich. So everyone should apply!

**Comment by bobby-digital-23** [comment]
I recommend you all follow Yi's suggestions. We'll all soon be using the software he creates at his new employer.  ;-)

Thanks @yiqin!
