### ISSUE TITLE
UI Image size too large

### ISSUE THREAD

**Issue by lw334** [uchicago-mobi/2016-Winter-Forum#44]
Didn't think following a tutorial will lead to many questions :P but I am having trouble with get the UIImange (from working with view controller) to show up as the right size. I followed all the steps specified by the tutorial and my uiimage is way off the screen. Anyone else have this problem? If you have any tips with sizing and adopting that to different devices please share! Thanks a lot!

**Comment by susanstevens** [comment]
@lw334 It looks like the UIImageView should be inside of a stack view, so I'd suggest double-checking that.  It can be a little tricky when you're dragging and dropping elements in storyboard to make sure that your view hierarchy is correct.

**Comment by vhicks** [comment]
I confirmed that my Imageview is in the stackview however I still see position issues. ~~It is not centering properly. I sized and set the constraints as given in the tutorial it still looks wrong in the simulator.~~

It was the size of my no photo selected image. Good to go now!
