### ISSUE TITLE
The 10th Point

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#49]
I know the assignment says to comment **all** functions and variables, but does that include when we fill in built-in functions (like `UITextFieldDelegate` functions, `UIImagePickerControllerDelegate` functions, the `viewDidLoad` function, etc)? These functions already have descriptions built in when you option-click on them, so wouldn't it be unnecessary to comment them myself?

**Comment by tabinks** [comment]
Your commenting will not override the built-in functions, but you should comment what you are doing inside the functions.  Comments don't have to be long, just informative.
