### ISSUE TITLE
Preferred iOS SDK

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#5]
Between the pre-release and stable SDK, which should we use for our apps?

**Comment by nicholasfasolt** [comment]
I remember Andrew telling us to use the stable versions in class.

**Comment by tabinks** [comment]
Use the latest one in the Mac App Store:
![screenshot 2016-01-06 11 15 11](https://cloud.githubusercontent.com/assets/93689/12148991/0748c722-b467-11e5-8e65-21946056ac03.png)

**Comment by ghost** [comment]
Ah whoops, I thought I was downloading an SDK from developer.apple.com but it was a pre-release version of iOS. Nevermind
