### ISSUE TITLE
More About 3D Touch

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#51]
Speaking of 3D Touch...
- [Apple Highlights 3D Touch in New Ad](https://www.macstories.net/news/apple-highlights-3d-touch-in-new-iphone-6s-ad/) Sidenote - [Macstories](https://macstories.net) is a great resource for Apple news and really innovative apps
- [Beyond Peak and Pop](https://medium.com/produkt-blog/3d-force-touch-beyond-peek-pop-c448edc2b1f5#.4h6gmh9qs): iOS developer being creative
- [Exploring Apple's 3D Touch (pretty technical post)](https://medium.com/@rknla/exploring-apple-s-3d-touch-f5980ef45af5#.i2mh56stm)

**Comment by tabinks** [comment]
Here is a description of how the Apple Pencil [works](http://9to5mac.com/2015/11/24/review-apple-pencil-for-ipad-pro/):

> That’s because the iPad Pro display refreshes 240 times per second to detect Apple Pencil, which is twice the refresh rate it uses for touch input with your fingers.
