### ISSUE TITLE
Office Hours Tonight: 6pm - 8pm @ Gleacher

### ISSUE THREAD

**Issue by danakatz** [uchicago-mobi/2016-Winter-Forum#52]
Come get an early start on this week's assignment! Also, the cafe has tasty food.

**Comment by nicholasfasolt** [comment]
Ha - was literally just emailing you that I'd attend tonight.

**Comment by danakatz** [comment]
@nicholasfasolt great, see you there!

**Comment by tabinks** [comment]
Yeah!  The forums work :+1:

**Comment by nicholasfasolt** [comment]
Where do you usually meet in Gleacher? The room on the south end of the 1st floor was just pretty packed when I got here so I'm in Graham's study lounge in the basement for now.

**Comment by danakatz** [comment]
@nicholasfasolt the cafe will clear out right at 6 when class starts. That's where I'll be :)

**Comment by nicholasfasolt** [comment]
Perfect, I'll head up in a little bit then.
