### ISSUE TITLE
Assignment 4 - Links and Tips

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#55]
I am going to post links to things that are especially pertinent to this assignment in this issue.  These will all be cross-posted on the [Session 4](http://uchicago.mobi/sessions/session4/index.html) page If you have any questions about the assignment, please open a new issue.

Assignment Write-Up:  [Session 4](http://uchicago.mobi/sessions/session4/index.html)
GitHub Classroom: Repository [Link](https://classroom.github.com/assignment-invitations/b582369935ef5f34c416ec792087ff52)

Example view controller with networking code for downloading GitHub issues: https://gist.github.com/tabinks/f40f0c13dde6ac104709#file-gistfile1-swift

View the JSON response for the Issues API: https://api.github.com/repos/uchicago-mobi/2016-Winter-Forum/issues?state=open

**Comment by tabinks** [comment]
Working with JSON in Swift:
 - [Swift Tutorial: Working with JSON](http://www.raywenderlich.com/120442/swift-json-tutorial)

Guard Statement:
- [guard and defer](http://nshipster.com/guard-and-defer/)

**Comment by tabinks** [comment]
# Links

Working with JSON in Swift:
- [Swift Tutorial: Working with JSON](http://www.raywenderlich.com/120442/swift-json-tutorial)

Guard Statement:
- [guard and defer](http://nshipster.com/guard-and-defer/)
- [Migrating to guard](http://ericasadun.com/2015/12/29/migrating-ifs-to-guards-in-swift/)
- [A case against the guard statement](http://ericasadun.com/2016/01/01/another-take-on-guard/)

Segue and View Controllers:
- [Apple Documentation on Segues](https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/UsingSegues.html)

Pull-to-Refresh:
- [UIRefreshControl from Apple Docs](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIRefreshControl_class/)
- [Basics of Pull to Refresh](https://www.andrewcbancroft.com/2015/03/17/basics-of-pull-to-refresh-for-swift-developers/)

Formatting Dates:
- [Apple Docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSDateFormatter_Class/)
- [NSFormatter - NSHipster](http://nshipster.com/nsformatter/)

Core Graphics:
- [Core Graphics Tutorial Part 1: Getting Started - R](http://www.raywenderlich.com/90690/modern-core-graphics-with-swift-part-1)

NSURLSession:
- [NSURLSession tutorial from Ray Wenderlich](http://www.raywenderlich.com/51127/nsurlsession-tutorial)
- [Objc.io on NSURLSession](http://www.objc.io/issue-5/from-nsurlconnection-to-nsurlsession.html)

**Comment by lw334** [comment]
Thanks for posting the resources! However, I don't think the link is creating a repository for me.

**Comment by shuaib88** [comment]
same for me

**Comment by tabinks** [comment]
I fixed it.

**Comment by tabinks** [comment]
Inspiration from last year:

![screenshot 2016-01-26 16 14 00](https://cloud.githubusercontent.com/assets/93689/12596880/d6057d72-c447-11e5-9a56-236bda74dfa2.png)

**Comment by tabinks** [comment]
# Attributions

Please do not forget about the new `/// - Attributions:` comment.  You should use it as follows:

``` swift
/// Shuffles an array of `Strings`
/// - Parameter array: An array of strings to be shuffled
/// - Return: An array of strings
/// - Attributions: http://stackoverflow.com/questions/24026510/how-do-i-shuffle-an-array-in-swift
func shuffleArray(array: [String]) -> [String] {
  ...
}
```

Before your final commit, extract all of your attribution comments and copy them to the README.md file in your project:

```
grep "/// - Attributions:" *.swift | pbcopy
```

**Comment by 3sands** [comment]
Can we also do:

```
/** Shuffles an array of `Strings`
 - Parameter array: An array of strings to be shuffled
 - Return: An array of strings
 - Attributions: http://stackoverflow.com/questions/24026510/how-do-i-shuffle-an-array-in-swift
*/
func shuffleArray(array: [String]) -> [String] {
  ...
}

```

**Comment by tabinks** [comment]
@dreisands Yes, of course.  I'm not sure why Swift supports both styles of comments, but it does.  I personally use to be a big fan of `/** */`, but have recently converted to the `///` since this is supported in Playgrounds for [markdown documentation markup](https://developer.apple.com/library/ios/documentation/Xcode/Reference/xcode_markup_formatting_ref/index.html#//apple_ref/doc/uid/TP40016497).
