### ISSUE TITLE
pass data between view controller 

### ISSUE THREAD

**Issue by lw334** [uchicago-mobi/2016-Winter-Forum#57]
Vaguely recall that the professor mentioned something about not loading the data until you necessarily have to when going from tab to tab.. I'm wondering if the best practice for this assignment is to load data once on initialization and just pass it through the different view controllers? Should we be able to refresh the data regardless what tab we are on? Thanks!

**Comment by susanstevens** [comment]
@lw334 You'll need to be able to refresh the data on both the "open issues" tab and the "all issues" tab, so you probably won't be passing any data between those two.  However, you don't need to refresh data on the last tab (the one with the circles), so you might want to send data from "all issues" over to your circles.

**Comment by tabinks** [comment]
Agreed.  You will be loading different data sets (open and all) for each view controller, so you should load the issues data in each view controller.  You could load the "all" data just once and then filter out the open, but this would be unnecessary work.  Your user will mostly be driving the data download and refresh with pull-to-refresh actions.
