### ISSUE TITLE
Office Hours - Friday @ TBD

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2016-Winter-Forum#63]
Please let me know if afternoon or evening works best  and at around what times. Thank you!

**Comment by shuaib88** [comment]
Afternoon Friday is great for me and 3pm would be not too late for a Friday. Since you have two office hours, perhaps Thursday could be evening and Friday could be afternoon?

**Comment by nicholasfasolt** [comment]
Ideally after 5:30 for me, if that's possible.

**Comment by nicholasfasolt** [comment]
(Sorry - thought I had responded to this sooner. I sent an email response to the post, which has worked in the past, but apparently it didn't go through.)

**Comment by brittneyli** [comment]
Friday(today) afternoon/late afternoon would be great for me too.

**Comment by msylvester** [comment]
@bobby-digital-23 anytime Friday would be outstanding

**Comment by bobby-digital-23** [comment]
Ok, would late afternoon to early evening for everyone who has replied - say approx 3:30-6:30pm in CSIL today? 

@nicholasfasolt I will try to stay later if possible. Please let me know if you can still make it to campus by 5:30pm. 

Btw, thanks all who've replied. :-)

**Comment by brittneyli** [comment]
SOUNDS AWESOME!

**Comment by nicholasfasolt** [comment]
**AGH!**

@bobby-digital-23 thank you, I really appreciate it. I had something come up last minute and now I'm not sure I'll be able to make it down to HP at all today. I will if I can. I'll let you know if/when I'm on my way if I can make it.

**Comment by bobby-digital-23** [comment]
Update:
I'll be doing 4:30-6:30pm. Additional evening office hours will go from 7:30pm to whenever. 

I received several more emails asking if I can do later evening hours. I'm starting later in case I need to stay  late tonight. Hope that's ok with everyone.  

Also, could anyone who is there at or before 4:30pm please send me an email? I might need your help getting into CSIL. My ID is still having issues. 

Also, please pick an area where no other office hours are being held and where we won't be bothering anyone by talking and let me know. CSIL is technically not part of the CS Dept but the director of CSIL was still kind enough to give us the space for the other days. I'd like to be respectful of him and his wonderful lab.  :-)

**Comment by bobby-digital-23** [comment]
@nicholasfasolt

No problem. Other people asked for evening office hours also. Just let me know if you'll be coming. Thanks!

**Comment by bobby-digital-23** [comment]
FYI - We're all in CSIL 1

**Comment by bobby-digital-23** [comment]
Anyone else planning on joining tonight? 

If yes, please post here or email me ASAP. 

Otherwise, I will be leaving after helping the students who are now. Thanks.

**Comment by bobby-digital-23** [comment]
Still going ;-)
