### ISSUE TITLE
iOS News - Parse is Shutting Down

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#64]
Parse was one of the, if not the, most popular back end solutions for iOS apps.  They were bought by Facebook last year (after Apple unsuccessfully tried to acquire them).  This is really surprising news and may cause a big shift if third-party solutions in iOS development.  Many developers will really be hesitant to use third-party solutions in their apps.

http://bits.blogs.nytimes.com/2016/01/28/facebook-to-shut-down-parse-its-platform-for-mobile-developers/?mwrsm=Facebook&_r=0

**Comment by tabinks** [comment]
FYI, in the Advanced class we explore and work with different backend solutions for iOS apps.  Almost every app (even a really trivial one) will have some sort of backend component to it.

**Comment by JRam13** [comment]
Bingo. You hit the nail on the head. 

We're (company I work for) going to have to start thinking in a few months about moving our backend. And the discussion will be, should we move into a custom backend, or a similar solution like Parse? Knowing that this can happen to any company out there, I think you're going to see less and less people choosing the MBAAS solution.

Major game changer.
