### ISSUE TITLE
Issues unwrapping data 

### ISSUE THREAD

**Issue by shuaib88** [uchicago-mobi/2016-Winter-Forum#67]
Has anyone gotten data to populate their table view? My view works fine with dummy data, and I can print github data to console but I keep getting a nil error on the issues Array when I try to use it in my table methods. 

![screen shot 2016-01-30 at 9 13 01 am](https://cloud.githubusercontent.com/assets/9851472/12696490/c287b9d0-c731-11e5-9e4b-1aa8e48a3798.png)

![screen shot 2016-01-30 at 9 14 17 am](https://cloud.githubusercontent.com/assets/9851472/12696494/e2ba226a-c731-11e5-9d95-13496c40a2e0.png)

**Comment by tabinks** [comment]
Think about if there is actually data in issues array at the time you are trying to access it.  If there isn't, then the table won't have any rows to show.

**Comment by shuaib88** [comment]
yeah that's what it looks like. i guess the tableview calls happen before the viewDidLoad calls. so issues is nil, but I"m not quite sure how to make those calls before the view is written or delay them until the call get's made.

One idea is to maybe use the init(coder:) to make the api call? 
http://roadfiresoftware.com/2015/01/ios-essentials-the-uiviewcontroller-lifecycle/

Maybe another is to use a guard statement on any calls to issues until it is not nil?

**Comment by shuaib88** [comment]
That's interesting.. the guard statements sort of delayed the execution of the issues calls until there was something there. But it looks like the first guard statement tried to execute 5 times, gave up and returned 10 for the number of rows. Then the 2nd guard statement tried to execute 5 times gave up and returned blank cells. Then when I scrolled the screen down, enough time had passed for the api call to be made and populate issues. 

![screen shot 2016-01-30 at 12 42 19 pm](https://cloud.githubusercontent.com/assets/9851472/12697676/4449eaac-c74f-11e5-9bc8-2313873f83f0.png)

**Comment by shuaib88** [comment]
so i ended up scrapping the guard, eric suggested using a while issues == nil {} to just wait for issues to populate. 

@tabinks was my use of guard just wildly inappropriate ;)?

**Comment by susanstevens** [comment]
@shuaib88 An empty while-loop works, but it wastes CPU cycles and definitely isn't best practice.  (Look up "busy waiting" for more on this.)  And I don't think I understand the guard idea.  Maybe you can explain it more.

It sounds like what you're looking for is a way to tell your table view that you've finished retrieving the data for it to display and that it should reload itself.  Luckily, there's a function built in to UITableView that does just that.  (It's got a very obvious name, and you should be able to find it fairly easily in the UITableView documentation.)

Fair warning - I'll probably be inclined to deduct points on any assignments using empty while-loops. :grimacing:

**Comment by JRam13** [comment]
Running a while loop on the main thread is a sure way to get yourself a deadlocked thread.

**Comment by bobby-digital-23** [comment]
@shuaib88 
I replied to your email and asked where you and Eric were using your while loop before I saw the rest of this thread. While I mentioned that a while loop can work (depending upon the context), I'd like to reiterate what Susan and Jonny noted, that does NOT mean that you should use an empty-while loop in the way that you're suggesting. That is bad practice and I will also be inclined to deduct points if I see that.

As suggested,please take a look at the tutorial from assignment 3 again and at Apple's documentation.

**Comment by lw334** [comment]
I am having the same problem and struggling to find a solution. If someone figured out how to solve the problem please give me hand here. Thanks a lot.

**Comment by tabinks** [comment]
Ask yourself 2 questions:
- If there is data in `issues`, how many rows should there be?
- If there is no data in `issues`, how many rows should there be?

**Comment by lw334** [comment]
Thanks!
