### ISSUE TITLE
Office Hours 4-6pm on Sunday

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Winter-Forum#69]
Reminder that I'll be in Crerar (specifically CSIL 1) tomorrow, Sunday, from 4-6pm to answer any questions!

**Next week, I'm planning to move my office hours to Sunday morning, most likely 10am to noon.**  I hear there's a big sporting event happening later in the day.  I'll post a reminder with the exact time next weekend.

**Comment by bobby-digital-23** [comment]
I heard something about the Australian Rugby Championship happening that day. ;-)
