### ISSUE TITLE
Prototype Cells not showing up properly

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#70]
For the All Issues tab, I've designed prototype cells, created a class called `IssueTableViewCell`, and hooked up the UI elements to in that class. In storyboard, I've changed the class to `IssueTableViewCell` and use the identifier `IssueTableViewCell`. In the `cellForRowAtIndexPath` method in IssueTableViewController.swift, I set up "IssueTableViewCell" as the cell identifier. **Essentially, I followed the Apple tutorial we used for the FoodTracker app to make sure I completed all of the necessary steps to get the table view cells to look like the prototype cells, but they don't.** What else can I do?
![screen shot 2016-01-31 at 11 15 13 am](https://cloud.githubusercontent.com/assets/11274851/12703567/11af9e4e-c80c-11e5-9c0f-b4a298617eb7.png)
![screen shot 2016-01-31 at 11 16 05 am](https://cloud.githubusercontent.com/assets/11274851/12703568/141cd066-c80c-11e5-8d8a-2b8c9276749a.png)

**Comment by aaizuss** [comment]
Update: Now it just shows usernames and dates - this is a result of selecting the cell and choosing "Add Missing Constraints" so I guess I have to experiment with constraints until the data appears properly.

**Comment by cjhodnefield** [comment]
@aaizuss I'm having this same issue. If you figure out the solution, please let me know. If I figure anything out while fiddling with it, I'll post it here.

To the instructors: Does this have anything to do with Auto Layout? Should we be using Auto Layout for this assignment or no?

**Comment by gopalp19** [comment]
Does your Table View have the Row Height amount set to the same amount as your IssueTableViewCell Row Height? I have both those set to 90 in the Size Inspector section.

**Comment by cjhodnefield** [comment]
Mine didn't at first, but I actually just caught that and changed it, and the problem still persists. I'm currently comparing my FoodTracker TableView side by side with the current assignment to see where the difference might be.

**Comment by cjhodnefield** [comment]
@gopalp19 Actually, scratch that. I fixed the Row Height in one TableView, but not both. It works now!

@aaizuss Did you try this Row Height fix?

**Comment by aaizuss** [comment]
Yep! The inconsistent row height was the issue (I only had IssueTableViewCell row height set to 90).
