### ISSUE TITLE
Segue from IssueTableViewController to IssueDetailViewController not working

### ISSUE THREAD

**Issue by cjhodnefield** [uchicago-mobi/2016-Winter-Forum#72]
I tried to imitate material we learned in the FoodTracker to seque from IssueViewController to IssueDetailViewController after clicking on a particular cell in the TableView.

I implemented prepareForSegue in the TableView the same way we did in the FoodTracker (with a correct segue.identifier), but nothing happens when I click on a cell. As far as I can tell from combing over the previous assignment's tutorial and my own FoodTracker project, that's the only thing we did to allow that segue to work (other than attaching the two views in storyboard of course). What am I missing?

**Comment by danakatz** [comment]
@cjhodnefield Did you check the box for "User Interaction Enabled" in storyboard?

**Comment by cjhodnefield** [comment]
@danakatz Do you mean that box for the IssueTableViewCell? If so, then, yeah, I checked that one already. It also changes color when clicked right now, which I think shows that interaction is working. Is there a similar box for UITableView or something?

**Comment by tabinks** [comment]
Make sure that you made the connection to the correct view when you dragged and drop.  You may have accidentally dragged from the view controller's main view (I'm guessing).  Sometimes it is difficult to tell exactly which view you dragged from.  You can check this by looking at the connection inspector the 4th tab in the inspector pane in Xcode.

**Comment by cjhodnefield** [comment]
@tabinks Ah, I think that's exactly what happened. I'm guessing you thought I dragged from the main view and not the cell? Because that's what I did. :)

Once I replaced the segue with one from the cell to the other view, it worked! Thanks!
