### ISSUE TITLE
Prototype cells not appearing as designed

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#73]
I configure the cell layout in the storyboard (as in the FoodTracker project), and define the cell in code so that it can be accessed and configured programmatically. But then, upon loading, the cells do not display as configured in the storyboard (though they load the appropriate data). How do I remedy this?

**Comment by cjhodnefield** [comment]
#70 - Does the content of this post address your issue? It was closed after we figured it out, so you may not have noticed it.

**Comment by ghost** [comment]
Yeah, that solved it. Thanks!
