### ISSUE TITLE
Changing label color by row

### ISSUE THREAD

**Issue by cjhodnefield** [uchicago-mobi/2016-Winter-Forum#75]
How do we change the color of the text of a UILabel to a different color on each line? Is this covered anywhere in this provided tutorial? I haven't made it through all the parts yet.

http://www.raywenderlich.com/90690/modern-core-graphics-with-swift-part-1

**Comment by susanstevens** [comment]
@cjhodnefield You _could_ use NSAttributedString (which we may or may not cover later in the course).  But you can achieve the same effect by using two labels.

This isn't related to core graphics and it's not a requirement for the assignment, so don't spend too much time worrying about it.

**Comment by tabinks** [comment]
Attributed strings are in week 1 of advanced class.

**Comment by tabinks** [comment]
You can set the text color directly on a uilabel, no need to use nsattributed strings.  You could but it's more complex.

**Comment by cjhodnefield** [comment]
Oh, if two labels is an option, that sounds easy enough. Thank you!
