### ISSUE TITLE
Issue Detail View: TextView does not display text, even static text

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Winter-Forum#76]
My `IssueDetailViewController` almost works: the app shows the body of the issue, formatted date, username, and status, but the title of the issue does not appear. I know that I get the correct title because I added a print statement, which appears in the log. I also tried setting the text to a constant "this is a test," by doing `issueTitleTextView.text = "this is a test"` and that doesn't show up either. I'm using a TextView for the title (as opposed to a Label so the whole title shows in case it's a long title), and it's definitely connected properly (I've checked + all the other elements are working). Initially, I thought it was a TextView issue, but I successfully show the issue body in a TextView by changing its `.text` property.

Am I missing something?

**Comment by danakatz** [comment]
@aaizuss Could this be a layout issue? Have you tried setting the text in storyboard, or adding a border or background color to make sure the text view is where you expect it to be?

If you'd like to use a label, which might be easier in this situation, you actually can have a label with multiple lines that will adapt to the length of its text. Checkout the **Sizing the Label's Text** section of the UILabel class [documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UILabel_Class/).

**Comment by aaizuss** [comment]
@danakatz Setting the text in storyboard worked but I couldn't figure out how to make text show up. I ended up using a UILabel instead, and everything works now. Thanks!
