### ISSUE TITLE
One UILabel appears per TableViewCell

### ISSUE THREAD

**Issue by ghost** [uchicago-mobi/2016-Winter-Forum#77]
I've 3 UILabels per TableViewCell, and they are connected and interfaced with accordingly. However, only the UILabel which displays the description appears in the cell. The username and timestamp labels do not, though their properties can be defined and the labels appear in the storyboard.

I've been toggling various options in vain for a while now. How do I resolve this?

**Comment by hbennett766** [comment]
In your table view controller, how are you calling the username and timestamp? Eg: let description = ....., let username = ....., and let timestamp = ..... In other words, make sure you're calling JSON correctly. Maybe you have the description correct and not the other two? Just starting from square one here, not sure what you've tried thus far.

**Comment by ghost** [comment]
Ah, there was an error in the Issue class that stores the JSON data.
