### ISSUE TITLE
updating CircleViewController with timely data

### ISSUE THREAD

**Issue by shuaib88** [uchicago-mobi/2016-Winter-Forum#78]
I'm trying to get fresh data in my CircleViewController just like I did in my Table View Controller. In my Issue Table View Controllers, I made a call to dispatch_async() in my viewDidLoad method like so:

![screen shot 2016-02-01 at 12 07 41 am](https://cloud.githubusercontent.com/assets/9851472/12710038/d899666e-c877-11e5-9041-87a4e814dedd.png)

I refreshed the tableView with reloadData(), which works great. But I'm searching for the equivalent for my CircleViewController. 

Would I update self.view somehow? It doesn't have any reloadData() method so that's where I'm stuck. Any hints in the right direction would be appreciated.

**Comment by lw334** [comment]
same issue heere let me know if you figured it out. thanks a lot!

**Comment by prazgaitis** [comment]
You can use the same method as you did for the table. Instead of refreshing a table, what do you want to do with the you have the data? 

Instead of a "pull to refresh" I update data each time the tab is loaded.

**Comment by lw334** [comment]
I found this helpful!  
 https://thatthinginswift.com/background-threads/

**Comment by shuaib88** [comment]
@prazgaitis that's interesting, I think we might have implemented the refresh differently, but what does your original dispatch_async() method look like? 

in your final method do you reference a touch event to get to the tab?

@lw334 in your case which task are you specifying? It's funny that dispatch_async() just sort of works without me specifying a specific task for the issue Controllers.

**Comment by lw334** [comment]
I specified the task to find the numbers of open/closed issues. Not sure.

**Comment by aaizuss** [comment]
@shuaib88 I'm trying to do the same thing in my CircleViewController - did you figure it out?

**Comment by shuaib88** [comment]
yup -- basically @prazgaitis comment led me in the right direction. 

anything you want to load with the right data, you have to place in the body of that asynch_dispatch function.
