### ISSUE TITLE
Getting NSDates properly

### ISSUE THREAD

**Issue by cjhodnefield** [uchicago-mobi/2016-Winter-Forum#79]
I thought I got this working a long time ago, but I just figured out that it isn't working how I thought.

How are we supposed to get the dates from the JSON response? Do we read them in as NSDates? Or do we have to use NSDateFormatter to convert them from Strings to NSDates? If so, what is the dateFormat that the dates are in coming from the JSON?

I tried to answer all these question using the provided NSDateFormatter links (and many google searches), but everything I tried failed and I'm at a loss. I feel like I'm missing something obvious.

**Comment by shuaib88** [comment]
I think the input is iso 0861 I used 2 NSDateFormatters, one to convert to an NSDate object and then the other to get the data in the form I needed. 

http://stackoverflow.com/questions/5185230/converting-an-iso-8601-timestamp-into-an-nsdate-how-does-one-deal-with-the-utc

**Comment by scj0055** [comment]
I converted from string to date, then back to string to set the text field's text property. I probably can't give you the exact date format string, but look at the API response and go from there. If you don't set the format string correctly, the formatter object will return nil. 

http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns 

Section 8 in the above link should also be helpful.

**Comment by cjhodnefield** [comment]
Thanks for the links. I've tried about 30 different dateFormat strings now. I just can't seem to get anything to work, despite reading through these links. I think it's the final part of my string that's the problem, after the seconds pattern. Can someone tell me how to handle the Z, or time zone, portion of the format string?

**Comment by cjhodnefield** [comment]
Actually, I just got it to work. Suffice to say, it wasn't that I was using an incorrect dateFormat in the end, it was another bug. Thanks for the help!
