### ISSUE TITLE
API Rate Limit Exceeded: Solution

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/2016-Winter-Forum#85]
My simulator has suddenly stopped loading tables, and I'm getting this message when I follow the url. Is there any way to resolve this issue from my end?

{
  "message": "API rate limit exceeded for 128.135.100.107. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}

**Comment by msylvester** [comment]
@hbennett766 

ditto

**Comment by tabinks** [comment]
@hbennet766 @mysylvester

I put a copy of the data as a gist.  Change your URL to the following for testing.  Note, it will not be current.  After 60 minutes, change back to the original URL.

## All Issues

```
https://gist.githubusercontent.com/tabinks/9382bf2468504e3a6d39/raw/214ec817c1e8698fe2f016582f41a4f64b6002a5/all.json`
```

## Open Issues

```
https://gist.githubusercontent.com/tabinks/63c27a6368aff643f477/raw/4c44f34f68fa477efcaf3b4cc7a4219ee7f1fa9e/open.json
```

**Comment by hbennett766** [comment]
Thank you!!!
