### ISSUE TITLE
centering circle

### ISSUE THREAD

**Issue by shuaib88** [uchicago-mobi/2016-Winter-Forum#88]
anyone have any tips on centering that bad boy? I'm hardcoding the coordinates of the center, but I'm sure there's a more precise way to do it.

**Comment by tabinks** [comment]
Check out the `CGRect` function helpers in Apple documentation.  There is one in I can think of that might might help a bit, but you still will end up having to do some calculations.  It will make you appreciate `UIView`'s center property.

**Comment by shuaib88** [comment]
I ended up using the center method of view (view.circleCenter = view.center) which worked pretty easily
