### ISSUE TITLE
What are we supposed to commit for the first homework?

### ISSUE THREAD

**Issue by brittneyli** [uchicago-mobi/2016-Winter-Forum#9]
I'm not quite sure what exactly we're supposed to be turning in... are we just committing the ViewController.swift and the Main.storyboard?

**Comment by tabinks** [comment]
You should commit your entire project.   This will include the view controller and storyboard, but also the other files that make up on Xcode project. Essentially, we will be able to run your entire app from what you submitted.

**Comment by cnfshandson** [comment]
Hi 
Two questions regarding the submission.
1) I am pretty new to github, saw the following in my private repo, 
"We recommend every repository include a README, LICENSE, and .gitignore"  I assume that is from github, not the requirement of the homework submission.

2) I am not sure what project to commit for assignment1. do you mean the project I create when learning the "Build a basic UI" and "Connect UI to code"? and the playground file? If so how do you want to grade the playground file and the project? I don't see any tasks in playground file, just some tutorial and experiment. Or I miss something. 

Thank you

**Comment by tabinks** [comment]
@cnfshandson 
1) Yes, those are GitHub recommendations.  You do not need to include them as part of the assignment.
2) Submit the entire project you built following the tutorial.  Include the playground file in the repo.  This is just to ensure that everyone at least downloaded the Playground and (hopefully) went through it.  Also, it's good practice to add and commit a file for those new to git.  There is nothing specifically to do for the playground.  Use it as you much/little as you need to become more familiar with Swift.

**Comment by cnfshandson** [comment]
Very clear. Thank you.

**Comment by bobby-digital-23** [comment]
@arcastar13
As Dr Binkowski stated, please commit your entire project. When you create a new project in Xcode, it will ask you what folder you want to use. In the Apple tutorial, this process is explained in "Create a New Project" in the "Build a Basic UI" section. That project folder you create is the one you want to post to your repo - it should contain all of the files for your project. 

An easy way to test if everything correctly posted to GitHub is to download the zip file (you'll see a link in your repo) and then run that project separately in Xcode. You'll quickly see if all of the required files are there and if anything is missing. :-)

Everybody:
Please remember you need to post TWO parts for assignment 1 to your GitHub repo:
The Playground
AND
The app based on the Apple tutorial, up until the section noted in the assignment instructions. 

Please also do the other requirements - creating an Apple Developer account, posting to the forum, etc. 

Everything required for assignment 1 is clearly explained here under "Assignment" :-)
http://uchicago.mobi/sessions/session1/index.html
