### ISSUE TITLE
NEW TIME - Office Hours Tonight - 5:30pm-7:30pm @ Gleacher

### ISSUE THREAD

**Issue by danakatz** [uchicago-mobi/2016-Winter-Forum#97]
I'm shifting my office hours half an hour earlier tonight. 
Please let me know if you plan on coming!

**Comment by nicholasfasolt** [comment]
See you there!

**Comment by joshuacalloway** [comment]
where in the gleacher is it?

**Comment by danakatz** [comment]
@joshuacalloway In the cafe on the first floor, across the lobby from the bookstore.

**Comment by joshuacalloway** [comment]
Ok, I'll be there 5:30 pm
