### ISSUE TITLE
App Challenge Programming Internship

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#98]
This is a fantastic program that many former students have taken part of.
#2016 Spring App Challenge Internship: Hone your mobile and web programming skills.

IT Services is looking for motivated, entrepreneurial programmers interested in building mobile and web apps.   As part of the final phase of the UChicago App Challenge (Spring quarter 2016), finalists will be paired with programmers to build a basic prototype of their developed app idea.   You will engage with IT professionals, clients and other stakeholders to build an app or a website.

Not sure?  Hear what it's like from Joe and Andrew (https://www.youtube.com/watch?v=-t-8v98lDlE)!
Still not sure?  Hear how it was for Julie and Alex (http://www.youtube.com/watch?v=J8GKw35JFvg)  and Adam and Josh (http://www.youtube.com/watch?v=-vukyjSN1qc).
## Structure

Meet with finalist team and get acquainted with project
Work with finalist team and UAC leadership to develop a roadmap for several iterations of the app or website.
Develop, test, and iterate a prototype of the solution.
Meet with finalist team for input
Help with testing
## Internship benefits

Experience working with clients in a professional IT setting
Mentoring from senior programming staff
A robust project for your portfolio
Opportunities to hone your programming skills
## When is it?

March 14, 2016 (if you'd like to start early) until June 2, 2016.  The intership does not start in earnest until March 28, the beginning of Spring quarter.
## Compensation

This is a paid, hourly internship.  We are offering competitive pay for this project, based on experience.
## Applying

If you are interested in applying for this opportunity, please fill out the webform here (https://appchallenge.uchicago.edu/content/deadline-february-12-apply-app-programming-internship-mobile-and-web)
https://appchallenge.uchicago.edu/content/deadline-february-12-apply-app-programming-internship-mobile-and-web

**Comment by JRam13** [comment]
I never did this myself, but I've heard great things about the program. 

Joe, Andrew, Julie, Alex! Man I miss those guys!

**Comment by susanstevens** [comment]
I did this internship last year!  I definitely recommend applying if you're looking to get some experience working in iOS development.

**Comment by jacksonding** [comment]
I am one of the teams in the App Challenge this year (the English learning platform I pitched in class two weeks ago). We have some great teams this year and I can probably get some additional information on the teams / project ideas if anyone is interested
