### ISSUE TITLE
Reminder: Please Close Resolved Issues

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Winter-Forum#99]
If you have opened an issue, once it is resolved (or not longer relevant), please close them.

**Comment by nicholasfasolt** [comment]
Should I close our evening office hours thread, or leave that open? That one hasn't been very active and we can always open another issue for office hour scheduling.

**Comment by tabinks** [comment]
Yes.  I believe the TAs have all the info from the survey to schedule their office hours.  Thanks.
